### ISSUE TITLE
V0.13.1 使用中发现的两个 bug

### ISSUE THREAD

**Issue by aquausora** [realth000/tsdm_client#1]
> 设备：Google Pixel 6
> 系统：Android 14

- 足迹版的帖子无法正常显示，点进去显示 `没有帖子`
- 回复功能无法使用，体现为点击纸飞机发送图标后，反馈了加载动画，却无事发生；但编辑功能正常，点击发送图标后，会提示「编辑成功」

以上问题非此版本专有，但是鉴于包括作者大佬及兽人萨尔在内的坛友似乎都可以正常使用回复功能，严重怀疑无法回复问题为 Pixel 或 Android 14 专有。

**Comment by realth000** [comment]
感谢反馈。

你的账号有足迹区的版主权限嘛，这两个问题都是因为缺乏适配具有版主权限的账号（）

1. 有版区操作权限的话，页面结构变了，拿不到分区里的帖子信息，这两天会修。
2. 回复功能无法使用但编辑功能正常已经在master分支修复了，同样是因为版主有点评权限，页面结构不一样。可以先用[这次action](https://github.com/realth000/tsdm_client/actions/runs/9844866648)编出来的。
3. 还有什么评分不能手动输入理由的问题，也是同样原因，还没修复。

~~也就这两天刚能修这些问题~~

下个版本估计要月末才发，问题1.和问题3.等修复以后我再跑一下action吧，先用那里面的凑合一下。

**Comment by aquausora** [comment]
~大佬好肝啊，那么晚还在回复~
用小号测试过了，确实如此，竟然是因为版主权限的原因x
是挂了实习之后发现的吧XD
