### ISSUE TITLE
macOS下无法连接网络

### ISSUE THREAD

**Issue by myp0402** [realth000/tsdm_client#10]
uname: `Darwin bogon 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64`
在相同网络环境下 使用Windows虚拟机可以正常登录和访问 但在macOS下连接失败
flutter完全没接触过 没找到debug mode（尬
![](https://files.catbox.moe/82hjuh.png)

**Comment by realth000** [comment]
感谢反馈。

应该是没有申请权限的原因。刚才尝试加上了，可以试试这里的包：https://github.com/realth000/tsdm_client/actions/runs/11161766345

我没有macOS的设备，虚拟机只能开opengl开不了metal，而flutter在mac上已经是纯metal，所以实在测不了。

上个测试版本没打出来mac和iphone的包，在下个版本出来之前都可以用上面链接里打的包。

**Comment by myp0402** [comment]
问题已经解决了 十分感谢

目前使用没有问题











--

<a href="https://imgtu.com/i/qYaMan"><img src="https://s1.ax1x.com/2022/03/25/qYaMan.jpg" alt="qYaMan.jpg" border="0" /></a>




在 2024-10-03 20:35:20，"realth000" ***@***.***> 写道：

感谢反馈。

应该是没有申请权限的原因。刚才尝试加上了，可以试试这里的包：https://github.com/realth000/tsdm_client/actions/runs/11161766345

我没有macOS的设备，虚拟机只能开opengl开不了metal，而flutter在mac上已经是纯metal，所以实在测不了。

上个测试版本没打出来mac和iphone的包，在下个版本出来之前都可以用上面链接里打的包。

**Comment by realth000** [comment]
> 问题已经解决了 十分感谢 目前使用没有问题
> […](#)
> -- <a href="https://imgtu.com/i/qYaMan"><img src="https://s1.ax1x.com/2022/03/25/qYaMan.jpg" alt="qYaMan.jpg" border="0" /></a> 在 2024-10-03 20:35:20，"realth000" ***@***.***> 写道： 感谢反馈。 应该是没有申请权限的原因。刚才尝试加上了，可以试试这里的包：https://github.com/realth000/tsdm_client/actions/runs/11161766345 我没有macOS的设备，虚拟机只能开opengl开不了metal，而flutter在mac上已经是纯metal，所以实在测不了。 上个测试版本没打出来mac和iphone的包，在下个版本出来之前都可以用上面链接里打的包。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

好的，那这个issue就关掉了，有疑问或者问题尽管开新issue。
