### ISSUE TITLE
关于若闲小阁区的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#101]
能否给这个区加一个统计第一页帖子该用户的贴最后回复数，因为这个区不是有第一个该用户最后回复超10条就得罚了吗，加了这个能快速确认是否超数了

**Comment by realth000** [comment]
要加的话还是给所有分区加，这个等考虑一下吧

**Comment by Qing-Novel** [comment]
> 要加的话还是给所有分区加，这个等考虑一下吧

好的

**Comment by realth000** [comment]
这个还是不加了，要留在分区的最后一页才有效果，而且不实时刷新帖子列表的话其他人新发的回复无法纳入统计里，会导致统计和实际有误差。

**Comment by Qing-Novel** [comment]
好吧
