### ISSUE TITLE
批量发帖功能

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#102]
未来能做个批量发帖功能吗，做成浏览器那种多窗口就行，新建多个发帖窗口然后切换发帖（随附两张浏览器截图做示意）
![Screenshot_20241123_154428](https://github.com/user-attachments/assets/dd5958ca-1fc5-4449-ad34-03530413e8d4)
![Screenshot_20241123_154434_com huawei browser](https://github.com/user-attachments/assets/e7cb9cd2-ea94-42ab-a4c6-9330bd7ef946)

**Comment by Qing-Novel** [comment]
因为有时候发epub一次发好几个，app一个一个的发效率太低了，网页就可以新建好几个窗口发帖

**Comment by realth000** [comment]
不会做，改动大，路由缓存ui都要改，而且感觉不算常用功能。

**Comment by realth000** [comment]
发帖是比较危险的功能，批量操作会克制一些

**Comment by Qing-Novel** [comment]
好的
