### ISSUE TITLE
被@后的马上回复会跳转到浏览器回复

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#108]
希望能适配下，直接app内回复

https://github.com/user-attachments/assets/297b1910-7393-48a2-9ca2-48e67879f6fd

**Comment by realth000** [comment]
这个艾特的提醒显示不出完整的艾特信息，多半还要去帖子里看。
而且回复的页面是个单独的，不在聊天页面里，用得不多，就不做了吧

**Comment by Qing-Novel** [comment]
> 这个艾特的提醒显示不出完整的艾特信息，多半还要去帖子里看。 而且回复的页面是个单独的，不在聊天页面里，用得不多，就不做了吧

好吧。。。主要是我下意识直接点了马上回复，然后跳到网页了。。
