### ISSUE TITLE
一些其他的请求

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#11]
作者您知道深夜读书会吗？想问下您这边之后未来有可能给深夜读书会做第三方客户端吗？那个网站根tsdm一样都是那种模板网站（只是随便问问

**Comment by realth000** [comment]
不知道这个网站，应该不会做，精力和兴趣在这边。

~~可以自己上手来，不难的~~

**Comment by Qing-Novel** [comment]
> 不知道这个网站，应该不会做，精力和兴趣在这边。
> 
> ~可以自己上手来，不难的~

好的好的
