### ISSUE TITLE
提醒重复加载

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#112]
（签到的时候发现的，因为我这边偶尔第一次见到会失败，所以得重启一次软件）
第一次开软件加载出消息提醒后重启软件，之前加载的消息提醒会再一次加载，导致提醒数字和列表里的条目翻倍

https://github.com/user-attachments/assets/533fc6e7-5d16-4bf7-a233-fdd5b4b3f060

**Comment by realth000** [comment]
和95应该是一个问题
