### ISSUE TITLE
头像异常闪动

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#115]
https://github.com/user-attachments/assets/bab0e488-6e5d-4e0f-b641-c714b4b4df94

我现在头像得图床挂了还没修复，这个应该是调用缓存显示的

**Comment by Qing-Novel** [comment]
不像之前版本，刚进入app头像也会闪了，之前有缓存的话不会

Uploading petal_20241201_103454.mp4…

**Comment by realth000** [comment]
nnd似乎是昨天新做一个功能的时候把一部分改掉了，没提交进来。

等我验一下吧

**Comment by Qing-Novel** [comment]
> nnd似乎是昨天新做一个功能的时候把一部分改掉了，没提交进来。
> 
> 等我验一下吧

彳亍

**Comment by realth000** [comment]
看了一下我这里正常，感觉是缓存不对，设置里清一次缓存吧

**Comment by Qing-Novel** [comment]
昨天清掉缓存了
不过现在似乎没这个问题
很奇怪

**Comment by realth000** [comment]
现在我这也复现不出来了
