### ISSUE TITLE
主页背景处希望添加背景色

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#116]
感觉去掉背景后挺空的，动画还能看到有这么个区域，要么加个背景色吧

**Comment by Qing-Novel** [comment]
主题不是有深浅色吗，深色填充这块就好了啊

**Comment by Qing-Novel** [comment]
比如说把这块颜色上上去
![Screenshot_20241202_082344](https://github.com/user-attachments/assets/e76908d8-a33d-4c79-8a07-1f7e6456a493)

**Comment by Qing-Novel** [comment]
其实也能看待这个颜色，从下往上拉的时候，直接固定这个颜色就行了

https://github.com/user-attachments/assets/d078b990-547c-41ad-9466-801de275eff3

![Screenshot_20241202_190325_kzs th000 tsdm_client](https://github.com/user-attachments/assets/25dd5c33-0bb0-4330-867b-4fc7e4fe56c2)

**Comment by Qing-Novel** [comment]
麻烦看下吧

**Comment by realth000** [comment]
那个是appbar主体的颜色，会随着滚动距离改，但是头像上半部分那里做不到一模一样，会更难看，还是维持透明吧。

**Comment by Qing-Novel** [comment]
好吧
