### ISSUE TITLE
一些界面头像加载异常

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#117]
https://github.com/user-attachments/assets/3ecc4397-5581-4cd1-868f-e4c619fa9e4b

就算具体的聊天界面加载出来，但是私聊列表里还是不加载

**Comment by Qing-Novel** [comment]
> petal_20241201_233942.mp4 
> 就算具体的聊天界面加载出来，但是私聊列表里还是不加载

这个录屏里TSDM那个账号的头像格式是avif

**Comment by Qing-Novel** [comment]
https://github.com/user-attachments/assets/035318f4-b0cc-48a2-8cb4-2189cf2d257a

首页也有这个情况，看头像应该是官方默认的吧，但是还是有这个问题

**Comment by realth000** [comment]
我这里没有这个问题，在设置里清除过缓存吗

**Comment by realth000** [comment]
有一部分是有这个现象，元音待查
