### ISSUE TITLE
论坛卡片可跳转功能开启后部分分区卡片不显示子板块

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#12]
在打开论坛卡片可跳转功能后仅天使后花园和天使综合区的分区显示了子板块，像天使动漫音乐和天使休闲区的分区就不显示子板块https://github.com/user-attachments/assets/8987e1c4-e0d4-4153-88b5-0cbfff451f68

**Comment by realth000** [comment]
这个功能是为了保证功能尽量和网页上一致。

显示的是首页里分区名字下面的快捷入口（文字），不需要点到分区里面，首页就可以看到。

目前网页端只有后花园，综合区和事务所采用了这种布局，所以到app里也只有这三个大区有效果。

**Comment by Qing-Novel** [comment]
> 这个功能是为了保证功能尽量和网页上一致。
> 
> 显示的是首页里分区名字下面的快捷入口（文字），不需要点到分区里面，首页就可以看到。
> 
> 目前网页端只有后花园，综合区和事务所采用了这种布局，所以到app里也只有这三个大区有效果。

好的好的。

**Comment by Qing-Novel** [comment]
佬，这个issue可以关了
