### ISSUE TITLE
希望增加删除已经登陆的账户功能

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#121]
目前可以多账户的登陆，但是没法删除已经登陆的账户，希望能增加删除已登陆账户功能

**Comment by realth000** [comment]
现在先切过去注销吧，注销需要往服务器发请求

**Comment by Qing-Novel** [comment]
不是注销，是从这个界面里删掉，账号不注销
![Screenshot_20241204_222644_kzs th000 tsdm_client](https://github.com/user-attachments/assets/300cab66-b2e3-44ed-8df1-4fcd4e7b86e2)

**Comment by realth000** [comment]
删但是不注销没有意义啊

**Comment by Qing-Novel** [comment]
> 删但是不注销没有意义啊

应该这么说比较恰当，在切换账号页面取消某个账号的登陆，同时该账号条目从切换账号页面删除

**Comment by realth000** [comment]
注销要用对应账号的凭据往服务器发消息，暂时不在这个页面加了，怕数据会乱，切账户再注销比较稳

**Comment by Qing-Novel** [comment]
> 注销要用对应账号的凭据往服务器发消息，暂时不在这个页面加了，怕数据会乱，切账户再注销比较稳

不是注销，只是这个页面取消账号登录

**Comment by Qing-Novel** [comment]
还是说目前没打算计划做账号退出登录的功能？

**Comment by realth000** [comment]
取消登录就是注销啊，只是因为数据的原因，维持切过去账号再注销这种形式

**Comment by Qing-Novel** [comment]
> 取消登录就是注销啊，只是因为数据的原因，维持切过去账号再注销这种形式

呃，好的。那未来会增加快速退出账号登录的功能吗。比如长时间不使用某个账号，然后cookle过期了，正好打算退出登录，那这种情况下就可以用快速退出账号登录，而不是进入该账户主页退出登录（进入该账户意味需要重新登录）

**Comment by realth000** [comment]
cookie过期的情况目前基本没处理，那个不好测，后面会补上，那种情况不用发请求，直接删掉数据就行

**Comment by Qing-Novel** [comment]
> cookie过期的情况目前基本没处理，那个不好测，后面会补上，那种情况不用发请求，直接删掉数据就行

删数据？是删掉软件数据吗？那如果有两个账号，只一个账号有这个情况那。。。
后面会补是吗，那就坐等了（

**Comment by realth000** [comment]
只删登录失效的账号啊，这种算corner case，危害不大的话近期先不改了。
登录流程很乱，后面可能还会改实现

**Comment by Qing-Novel** [comment]
> 只删登录失效的账号啊，这种算corner case，危害不大的话近期先不改了。 登录流程很乱，后面可能还会改实现

行

**Comment by realth000** [comment]
现在的注销实际上并没有删账户的消息数据，只是把登录的信息删掉了，后面再加吧，一般来说也不应该删
