### ISSUE TITLE
希望私人消息和交谈记录界面可以查看用户主页

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#122]
https://github.com/user-attachments/assets/3e232bf1-72c2-4445-874a-1e9d35b41045

目前这两个界面看不了用户主页，希望私人消息和交谈记录界面可以查看用户主页

**Comment by realth000** [comment]
忘了加了

**Comment by Qing-Novel** [comment]
那后面加下吧（
然后刚才删账户那个，不是注销账户，是这个界面删掉账户
![Screenshot_20241204_222644_kzs th000 tsdm_client_edit_42221252201889](https://github.com/user-attachments/assets/43e065de-8a00-40c2-ab86-fbc6fbfefeae)

![Screenshot_20241204_222940_com huawei browser](https://github.com/user-attachments/assets/38290855-368f-489e-b0b1-65b5ef0196d2)
