### ISSUE TITLE
用户积分排行链接跳转到浏览器

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#123]
https://www.tsdm39.com/misc.php?mod=ranklist&type=member&view=credit
这个链接，希望能App内解析并查看

https://github.com/user-attachments/assets/bf2d5a01-5c57-482e-8abe-3e51a72ceb3f

**Comment by realth000** [comment]
emm其实可以做，但这种页面很多，而且没什么用，就先不放到计划里了，不然太多了

**Comment by Qing-Novel** [comment]
> emm其实可以做，但这种页面很多，而且没什么用，就先不放到计划里了，不然太多了

好吧
