### ISSUE TITLE
公共消息接收

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#124]
为啥我大号收不到这条消息，小号却收到了？不应该都有的吗
![Screenshot_20241206_224203_kzs th000 tsdm_client](https://github.com/user-attachments/assets/7dcf931c-18be-44d0-a5f7-bfd5f023ef7a)

**Comment by realth000** [comment]
看看网页端有没有吧，公共消息也不一定每个用户都有，我也没收到这个消息。

**Comment by Qing-Novel** [comment]
> 看看网页端有没有吧，公共消息也不一定每个用户都有，我也没收到这个消息。

好的，我看下我大号

**Comment by Qing-Novel** [comment]
好吧，我大号也没有
