### ISSUE TITLE
能不能把查看键调的大一点

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#125]
太小了，会误点到链接，导致消息提示不消失
![Screenshot_20241207_164224_kzs th000 tsdm_client_edit_31182379973365](https://github.com/user-attachments/assets/418020ee-f07b-4f95-8165-e77d98b2fc56)
要不移动到这块，这块地方有空间放放大的查看键

**Comment by realth000** [comment]
现在提醒不会区分类型，因为消息的类型太多，没有办法分别种类，不会像原来那样尝试区分什么消息是什么类别了，因此也就不会对消息里的链接做一些特殊识别（比如是查看链接）。

不会不消失，点击消息里任何一个会跳转到其他页面的链接都会把红点消掉，如果消不掉，可以点消息卡片右上角的菜单里标记成已读。
