### ISSUE TITLE
关于主页的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#127]
![IMG_20241209_091047](https://github.com/user-attachments/assets/6684da7e-1abe-41de-88c8-f4436c3843a4)
新版本的主页怎么说了，屏幕越小看着越别扭，能不能把签到或者消息像之前那样放在账户名那一行的右侧，剩下的功能两个一行？这样看着比较简介，不像这样非常的空

**Comment by Qing-Novel** [comment]
![mmexport1733707848920](https://github.com/user-attachments/assets/301c16b9-5682-4839-8aef-1004e8ce4d21)

**Comment by realth000** [comment]
考虑过，本来想做成正方形的，这样一排可以好几个，但是按照每个方形固定大小的话每一行末尾会有空白。

等等像谷歌商店那样做成右上角的头像吧，点开以后显示这部分内容，通知单独放外面和头像并列。

**Comment by realth000** [comment]
也能缓解一些这个页面太长的问题

**Comment by Qing-Novel** [comment]
> 考虑过，本来想做成正方形的，这样一排可以好几个，但是按照每个方形固定大小的话每一行末尾会有空白。
> 
> 等等像谷歌商店那样做成右上角的头像吧，点开以后显示这部分内容，通知单独放外面和头像并列。

好的

**Comment by Qing-Novel** [comment]
轮播页怎么也有背景了。。。。这个背景没必要加的吧，有点难看了
![Screenshot_20241209_152016](https://github.com/user-attachments/assets/f9e4a633-dc48-4505-88b2-7255db86c0ed)
![Screenshot_20241209_152011_kzs th000 tsdm_client](https://github.com/user-attachments/assets/056ee145-4a5e-40e8-84ec-ec285e9d917b)

**Comment by Qing-Novel** [comment]
这个首页加载页未来是不是也得改下了？
![Screenshot_20241209_162234_kzs th000 tsdm_client](https://github.com/user-attachments/assets/c9d2d744-b765-41cb-9bd0-4a0c606ab952)

**Comment by realth000** [comment]
会配套改

**Comment by Qing-Novel** [comment]
> 会配套改

彳亍

**Comment by Qing-Novel** [comment]
这个圆角里再整圆角，上下还有留白，感觉不太好看啊
![Screenshot_20241209_182527](https://github.com/user-attachments/assets/ccb8fb39-e0a1-4930-bddf-579145d0d402)
![Screenshot_20241209_182552](https://github.com/user-attachments/assets/7ea1ffd0-d205-4c7f-800e-14380dad52d4)

**Comment by Qing-Novel** [comment]
> 这个圆角里再整圆角，上下还有留白，感觉不太好看啊 ![Screenshot_20241209_182527](https://private-user-images.githubusercontent.com/136884931/393797523-ccb8fb39-e0a1-4930-bddf-579145d0d402.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDMwNjcsIm5iZiI6MTczMzc0Mjc2NywicGF0aCI6Ii8xMzY4ODQ5MzEvMzkzNzk3NTIzLWNjYjhmYjM5LWUwYTEtNDkzMC1iZGRmLTU3OTE0NWQwZDQwMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMTEyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODJhYjFmNTNhN2E5OGUzNTk4ODc4ZGMxZGRkYWQyMjljZTM4MmMyOTMwOGU2MWQzNzgxNDE5YTEzYTBmYTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f_LTcYIX0AEZKI4DGrmE0czRtSL4_Uv6iPZbe3mSDiM) ![Screenshot_20241209_182552](https://private-user-images.githubusercontent.com/136884931/393797552-7ea1ffd0-d205-4c7f-800e-14380dad52d4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDMwNjcsIm5iZiI6MTczMzc0Mjc2NywicGF0aCI6Ii8xMzY4ODQ5MzEvMzkzNzk3NTUyLTdlYTFmZmQwLWQyMDUtNGM3Zi04MDBlLTE0MzgwZGFkNTJkNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMTEyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWNiYWU3YmM1MmE4ODBmNThmMzMyOWRjMDBhNzcyZWMyYjg0YTdhNjdmM2E2MWNmNzNkZmNmMDc0N2I3ODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-2XAD55OAeXlPJ8PWwMV9CR67y8WaJj3PR04zPcVlco)

上一个版本没这个问题
![Screenshot_20241209_191239](https://github.com/user-attachments/assets/2b1c754b-d1e0-45fe-b3db-e63e689826cb)
![Screenshot_20241209_191217_kzs th000 tsdm_clienu](https://github.com/user-attachments/assets/a19f68bc-e919-4a79-9bff-85a5a597d0f6)

**Comment by realth000** [comment]
这问题有几个月了，懒得修，不关键（

**Comment by Qing-Novel** [comment]
> 切换成flutter自带的轮播图就有这个问题了，比社区的稳定一些但还是有不少bug。
> 
> 前几天尝试换个表现方式结果还不如现在的。
> 
> ui扣细节是一件很痛苦的事，等哪天受不了或者没活了再改吧，也可能改之前就重构掉了，比如论坛的api完全不包含主页这个tab的内容，换成api以后就只有分区了。

好吧，慢慢整吧。。
