### ISSUE TITLE
关于开屏页状态栏黑色的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#13]
![Videoframe_20241005_115241_com huawei photos](https://github.com/user-attachments/assets/cd589dd5-740e-4878-b10d-e70b6b6a1d66)

https://github.com/user-attachments/assets/d2b10bfb-73b6-45fb-838e-634485cbc9e8

发现这个问题也有段时间了，希望作者能改下，让状态栏跟下方的页面一个颜色

**Comment by realth000** [comment]
ok，会看看这个问题

**Comment by Qing-Novel** [comment]
> ok，会看看这个问题

好的好的

**Comment by Qing-Novel** [comment]
> ok，会看看这个问题

作者可以参考下FIClash这个软件

https://github.com/user-attachments/assets/674d3eca-dc38-4fe2-a126-4f8833ac3126

**Comment by Qing-Novel** [comment]
横屏也有这个问题
![Screenshot_20241013_184740_kzs th000 tsdm_client](https://github.com/user-attachments/assets/21a072d0-edc1-46f1-86f4-2cbcef4b5797)
理想效果是这样
![Screenshot_20241013_184830_com follow clash](https://github.com/user-attachments/assets/16255009-a93c-45fb-8859-0f2ae6cba7bd)

**Comment by Qing-Novel** [comment]
佬，这个问题隔壁的第三方真白萌修复了（虽然状态栏反色出了问题+横屏没做只做了竖屏）
https://github.com/qixiaoo/masiro/issues/20

**Comment by Qing-Novel** [comment]
可能是这个问题


> 佬，这个问题隔壁的第三方真白萌修复了（虽然状态栏反色出了问题+横屏没做只做了竖屏） [qixiaoo/masiro#20](https://github.com/qixiaoo/masiro/issues/20)

反色masiro的作者也搞定了，kazumi的作者貌似知道问题出在哪里了https://github.com/Predidit/Kazumi/issues/280?notification_referrer_id=NT_kwDOCCiyw7UxMjc2MDQyMDA4NDoxMzY4ODQ5MzE
![Screenshot_20241130_091000_com huawei browser](https://github.com/user-attachments/assets/d11ad84e-a2c2-4f5d-a3a9-0108ab11bcee)

**Comment by Qing-Novel** [comment]
这个问题能整吗？这两位作者目前都修复了（有使用flutter制作软件）
https://github.com/qixiaoo/masiro/issues/17
https://github.com/Predidit/Kazumi/issues/280
其中，在kazumi这个issue里，masiro作者有告知kazumi作者该问题产生的原因
![1](https://github.com/user-attachments/assets/3abe1e3f-8e2c-4526-99a5-844d965aa9ba)

**Comment by realth000** [comment]
可以的，你也可以提一个pr，改动很小

**Comment by Qing-Novel** [comment]
😂我也希望我能写代码方面的pr啊
