### ISSUE TITLE
关于签到的疑问

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#130]
想问下如果我开着软件一直不关，从晚上11点到2点（举个例子，表示使用期间有签到时期）那软件会自动签到吗，还是得重启软件才会签到？
然后现在签到换成api了吗？换了的话我去关我提的issue

**Comment by realth000** [comment]
不会，只有启动软件时才会签到。
还没有迁移到api，哪个issue？用不用api是内部细节，对用户来说是一样的

**Comment by Qing-Novel** [comment]
> 不会，只有启动软件时才会签到。 还没有迁移到api，哪个issue？用不用api是内部细节，对用户来说是一样的

好的
80号issue，就签到报错那个，我到今天还有报错就离大谱。。。。要是api签到能不报错的话那我觉得还是改成api签到吧

**Comment by realth000** [comment]
以后改吧
