### ISSUE TITLE
主页消息加载图标错位问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#131]
![Screenshot_20241211_132344_kzs th000 tsdm_client](https://github.com/user-attachments/assets/1aabefd0-fd73-4140-9976-dbd1ea6b3a98)
不是主要问题，然后如果主页要重构就没啥必要了，但是姑且先写个issue

https://github.com/user-attachments/assets/702e4f21-e7c9-43e7-86ee-14e9eeab61e6

**Comment by realth000** [comment]
已经重构了

**Comment by Qing-Novel** [comment]
彳亍
