### ISSUE TITLE
关于ui的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#132]
![Screenshot_20241213_081041](https://github.com/user-attachments/assets/bdb861ba-cbd0-42f8-8529-b343051ad176)

圈中的ui要不分区和设置也常驻吧？然后切换账号做到这里面吧
![Screenshot_20241213_081141_kzs th000 tsdm_client](https://github.com/user-attachments/assets/9106537b-0735-4fc4-a906-8dc83bf01f22)

**Comment by realth000** [comment]
右上角actions按照md的规范是建议不超过5个按钮，4个我觉得也挺挤，为此已经把打开链接的按钮塞进搜索页了。
消息和签到比较常用，而且有加载/不加载这种状态，放到对话框里不合适。搜索和当前登录的用户无关，也不能放进去。所以这四个按钮都没法去掉。

然后主页的内容是需要登录才能看的，分区和设置并不要求登录，而且分区和设置跟主页是并列的，不是从属关系。

实际上，主页和分区两个页面都是论坛首页的内容，把分区从首页里拆出来了，不然内容太多。

**Comment by Qing-Novel** [comment]
> 右上角actions按照md的规范是建议不超过5个按钮，4个我觉得也挺挤，为此已经把打开链接的按钮塞进搜索页了。 消息和签到比较常用，而且有加载/不加载这种状态，放到对话框里不合适。搜索和当前登录的用户无关，也不能放进去。所以这四个按钮都没法去掉。
> 
> 然后主页的内容是需要登录才能看的，分区和设置并不要求登录，而且分区和设置跟主页是并列的，不是从属关系。
> 
> 实际上，主页和分区两个页面都是论坛首页的内容，把分区从首页里拆出来了，不然内容太多。

好吧，那就维持1.0.0的版本吧（
