### ISSUE TITLE
发帖时添加回复后可见/折叠区域功能软件直接卡死，设备死机

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#134]
如图所示，本打算水区发一贴，结果居然出现了添加回复后可见直接卡死这个情况。。。

https://github.com/user-attachments/assets/c3f2711a-d20d-4ce7-95b4-c02b018ae02b

设备是aosp10，aosp12的设备也复现了该问题（在只是软件卡了的情况下赶紧清了后台）
太逆天了，我待会儿再试试别的功能卡不卡

**Comment by Qing-Novel** [comment]
草，折叠区域也卡

https://github.com/user-attachments/assets/33ef8736-fb14-4612-ae80-daba247ac2a4

幸亏赶紧删了后台，要不然就彻底卡死了

**Comment by realth000** [comment]
很不幸这应该是个flutter内部的问题：https://github.com/flutter/flutter/issues/117995

目前看来只能绕过去了，实在不行只能在Android上禁用折叠和隐藏区域这种功能，当然这是最坏的打算。

**Comment by Qing-Novel** [comment]
> 很不幸这应该是个flutter内部的问题：[flutter/flutter#117995](https://github.com/flutter/flutter/issues/117995)
> 
> 目前看来只能绕过去了，实在不行只能在Android上禁用折叠和隐藏区域这种功能，当然这是最坏的打算。

啊？？？
可是最开始加入这两个功能的版本却没这问题啊。。。
过于离谱了这也

**Comment by realth000** [comment]
最开始是哪两个版本，也在安卓上试过？

**Comment by Qing-Novel** [comment]
> 最开始是哪两个版本，也在安卓上试过？

加入这两个功能的版本，我看看是测试几版本
刚加入用的时候没问题的

**Comment by Qing-Novel** [comment]
更完正好就用了折叠区域这个功能

**Comment by Qing-Novel** [comment]
应该是测试13版，我现在重新搞下看看卡不卡

**Comment by Qing-Novel** [comment]
然后我会慢慢更新版本看看从哪个版本开始卡的

**Comment by realth000** [comment]
好我看一下，

**Comment by realth000** [comment]
你那不用更，我这更方便点

**Comment by Qing-Novel** [comment]
13版折叠+隐藏都没问题，14版折叠没问题，隐藏有问题，15版开始都有问题了

**Comment by Qing-Novel** [comment]
我记得是这俩功能有后更新了一次，用折叠没问题，正好跟测试结果一样。隐藏我之前是一直没用过，只用过折叠

**Comment by Qing-Novel** [comment]
13版本

https://github.com/user-attachments/assets/4f459ce2-f01d-47bd-af2e-c434b443efbf

**Comment by realth000** [comment]
ok，定位到了是这个提交 https://github.com/realth000/flutter_bbcode_editor/commit/6c9663d551a65df6cbf06f1c2c35248ea67a6198

我看看怎么个事。

**Comment by Qing-Novel** [comment]
14版本

https://github.com/user-attachments/assets/7d899f10-3eca-48b4-9027-b80a4aec3fbf


https://github.com/user-attachments/assets/6fcab8f0-6dab-4055-a436-191ff6cc5e2b

**Comment by Qing-Novel** [comment]
15版本

https://github.com/user-attachments/assets/d49d00f4-7fc3-4429-94e4-76de6b666769

**Comment by Qing-Novel** [comment]
> ok，定位到了是这个提交 [realth000/flutter_bbcode_editor@6c9663d](https://github.com/realth000/flutter_bbcode_editor/commit/6c9663d551a65df6cbf06f1c2c35248ea67a6198)
> 
> 我看看怎么个事。

OK👌

**Comment by realth000** [comment]
回退这个提交以后也有问题，不好说了

**Comment by realth000** [comment]
试着换一套实现吧，现在这套效果也不太好

**Comment by Qing-Novel** [comment]
> 回退这个提交以后也有问题，不好说了

嘶。。。。佬要不看看测试13版到14版改了啥吧

**Comment by Qing-Novel** [comment]
彳亍口巴，辛苦了

**Comment by realth000** [comment]
在安卓暂时改成插入spoiler和hide的源码了，新实现进度不快，问题比较多，可能还要魔改上游的代码。

**Comment by Qing-Novel** [comment]
> 在安卓暂时改成插入spoiler和hide的源码了，新实现进度不快，问题比较多，可能还要魔改上游的代码。

好的

**Comment by Qing-Novel** [comment]
> 在安卓暂时改成插入spoiler和hide的源码了，新实现进度不快，问题比较多，可能还要魔改上游的代码。

突然想到，要不跟添加链接的功能一样，点击后弹一个窗口填内容，确定后再插入对应的内容得了，这样会不会能解决卡顿问题？之前是点击后出现内容，然后再点击出现的内容填内容

**Comment by realth000** [comment]
没有明白。

你说的方式和现在的方式实际上是一样的，只不过折叠和hide里内容可能很多，不适合用dialog，才用一个单独的页面去做。

目前并不能确认问题出现的直接原因是什么，可能是因为导航到了另一个页面，可能是因为editor里又内嵌了一个editor。

我在想办法把这两个原因都绕过去。

上游里没有类似的issue，也没有类似的用法，二次开发的程度没有这么深，没有经验可借鉴。

另外上游马上要发布v11，想等v11出来了，合并一次，再修这个问题。
