### ISSUE TITLE
私信回复时的提醒不跟随键盘缩到屏幕底部

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#135]
https://github.com/user-attachments/assets/00bdc236-234a-47a3-9f7a-335db71b46d4

如录屏所示。。。然后帖子回复貌似？没这个问题、吧

https://github.com/user-attachments/assets/5a107f74-fab9-4543-a0af-65a1f9c40471

**Comment by Qing-Novel** [comment]
小屏模式下貌似可以缩到底下

https://github.com/user-attachments/assets/8223bc47-9721-4e75-8d26-6030805801b4

**Comment by realth000** [comment]
目前看是设计如此，先不改了。
