### ISSUE TITLE
主页关于大屏幕下的ui建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#138]
https://github.com/user-attachments/assets/04f8bccc-5f15-46ce-8b2f-f1d9cbc95f48

在大屏下，首页子模块会出现两个一排、三个一排的情况，会导致最底下发帖排行单个模块，有些突兀
要不在加个模块或者发帖排行拉长填充空白？

**Comment by Qing-Novel** [comment]
或者把最新活动单占一行，其他的正常两两三三配一行

**Comment by realth000** [comment]
算设计如此吧，大屏小屏不可兼得，现在布局已经考虑过了

**Comment by Qing-Novel** [comment]
> 算设计如此吧，大屏小屏不可兼得，现在布局已经考虑过了

好吧
