### ISSUE TITLE
关于首页右上角ui的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#140]
要不把历史记录从二级菜单拿出来替换主页右上角的签到？毕竟有自动签到这个功能估计用的人少，但历史记录用的人肯定多

**Comment by realth000** [comment]
签到有状态的，不这样改了。

**Comment by Qing-Novel** [comment]
> 签到有状态的，不这样改了。

好的，不过历史记录这个功能用的也挺多的，之后能看看放到容易用的地方吧。。。二级菜单有点深了这位置
