### ISSUE TITLE
关于多账号的疑问

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#142]
突然间想到的，比如我在设备A装了佬的app，登陆了1和2两个账户，平常A上只用1账户。然后我在设备B也装了佬的app，但是只登陆了2这个账户，同时我用2账户发了一些回复，那当我打开设备A的app（因为一直只用1账户所以app打开后显示的是1账户），那app会加载2账号的消息吗（我知道肯定不会系统推送提醒，但是会不会同步信息到app呢？）？

**Comment by realth000** [comment]
只会加载当前已登录用户的消息，不会同步其他用户的消息。

**Comment by Qing-Novel** [comment]
> 只会加载当前已登录用户的消息，不会同步其他用户的消息。

那之后可不可以加载呢？

**Comment by realth000** [comment]
不会做这个功能，不登录的用户接入需要登录的功能会改得很麻烦，不登录相当于不活动。

**Comment by Qing-Novel** [comment]
> 不会做这个功能，不登录的用户接入需要登录的功能会改得很麻烦，不登录相当于不活动。

好的

**Comment by Qing-Novel** [comment]
> 不会做这个功能，不登录的用户接入需要登录的功能会改得很麻烦，不登录相当于不活动。

好的
