### ISSUE TITLE
私信消息缩略存在问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#143]
今天无意间发现私信列表一位好友的最后一句话其实不是跟他聊天时的最后一句话，而是倒数第二句话，其他好友没这个问题（其实有，不过发完消息马上下拉刷新就恢复了，但是这条我发完没回复就退出私信列表了）

https://github.com/user-attachments/assets/79260990-c9a0-4f85-9465-b1d4861aab82

**Comment by realth000** [comment]
这是是正常的，因为最后一条是你发的，在下次拉取消息之前都会显示旧消息，拉取一次才会刷新。

和在帖子里回复以后，不显示最新回复的楼层同理。

**Comment by Qing-Novel** [comment]
> 这是是正常的，因为最后一条是你发的，在下次拉取消息之前都会显示旧消息，拉取一次才会刷新。
> 
> 和在帖子里回复以后，不显示最新回复的楼层同理。

不是的，视频里的这个自动和手动刷新都不变的

**Comment by Qing-Novel** [comment]
我待会儿发个对比视频

**Comment by Qing-Novel** [comment]
https://github.com/user-attachments/assets/b1e953ff-3444-4b9d-9346-f0aef666432c
