### ISSUE TITLE
电脑版软件图标固定到底栏时发现的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#148]
固定后图标显示异常，而且有时候会无法固定

https://github.com/user-attachments/assets/b8f24ad4-52d9-463a-9e0a-7a966af8c79d

**Comment by realth000** [comment]
这应该是windows的bug而不是应用，图标数据库是windows自己维护的，应用没有做任何事

**Comment by Qing-Novel** [comment]
> 这应该是windows的bug而不是应用，图标数据库是windows自己维护的，应用没有做任何事

好吧。。。。只能说过于离谱了。。。正好我更了一次系统。。。。

**Comment by Qing-Novel** [comment]
我再观察观察，要是别的电脑没问题那我就把这个issue关了

**Comment by Qing-Novel** [comment]
有点抽象，不过我把图标设定了下，先这样凑合吧，我先把issue关了
