### ISSUE TITLE
提醒消息接收异常

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#149]
同账号不同设备，接收这条消息的时候右设备正好切到小号，再切回来死活接收不到了（自动拉取和手动拉取都没用）

https://github.com/user-attachments/assets/632d887d-70ed-4a33-9989-79648a123f42

**Comment by Qing-Novel** [comment]
> 问题太多，砍了算了

嘶。。。。要是实在改不了就这样了，没提醒还是不太行。。。
或者要不网页+api两种途径加载消息？先api，后网页，api加载出来的消息网页提取到相同消息就不显示了？

**Comment by Qing-Novel** [comment]
> 自动拉取导致的问题太多，丢消息是比较严重的，本来更换底层实现就是为了稳定，现在看来没有达到效果。
> 
> 我怀疑即使去掉自动拉取也一样有很多问题。
> 
> 不能两种一起用，两者会相互干扰，而且取到的数据不同不能放一起比。
> 
> 和登录状态之间的相互影响比我之前预想的还大，之前料想过可能有问题已经加了一些手段预防，现在看来并没有防住。
> 
> 我遇到过一次消息导致cookie乱掉的问题，只是怀疑，应该是拉取消息导致的。只遇到过一次，但如果遇到了，后续的状态全是错的，从用户手段很难处理，哪怕加一些亡羊补牢的措施也比较麻烦。
> 
> 到处打补丁只能说明这个功能当时设计的时候就没有想好，今后继续打补丁同样会越来越乱。
> 
> 需要一些时间梳理下这个功能涉及的范围，考虑得周全一些。

emmmmm也就是说算是老问题了呗。。。
看样子得慢慢搞了。。

**Comment by realth000** [comment]
其实不算老，改了实现以后才有的这些问题。

当然之前的实现拥有的问题通过更换实现确实解决了，但这一套新实现新引入的问题就是另外一回事了，总的来说比之前强，但目前看来问题还是很多。

一部分bug我没遇到是因为我不开自动拉取，只手动刷新，所以平常使用不会遇到，功能上线前测试也不充分就是了（

**Comment by Qing-Novel** [comment]
> 其实不算老，改了实现以后才有的这些问题。
> 
> 当然之前的实现拥有的问题通过更换实现确实解决了，但这一套新实现新引入的问题就是另外一回事了，总的来说比之前强，但目前看来问题还是很多。
> 
> 一部分bug我没遇到是因为我不开自动拉取，只手动刷新，所以平常使用不会遇到，功能上线前测试也不充分就是了（

我这边遇到送的异常主要是长时间使用软件，比如打开软件后就不管了或者小窗模式打开软件后就缩小放一边，一有消息就回复，如果是偶尔开一次软件的话就正常，消息全能收到且没问题。。。感觉是长期使用时自动接收的问题（不过长时间不开偶尔开的话会遇到打开软件后信息加载不全的问题，不过这个问题是1.8正式版才有的）

**Comment by Qing-Novel** [comment]
感觉佬有啥功能做完后可以让我帮测试下（

**Comment by realth000** [comment]
暂时把这部分功能去掉了

**Comment by Qing-Novel** [comment]
> 暂时把这部分功能去掉了

啥意思？就没法收消息了？

**Comment by Qing-Novel** [comment]
> 暂时把这部分功能去掉了

是把消息提醒功能去掉了是吗？然后未来会加回吗？

**Comment by realth000** [comment]
把自动收消息去掉了

**Comment by Qing-Novel** [comment]
> 把自动收消息去掉了

呃，有点伤啊。。我多少还是在用这个功能的
佬是打算重做自动收消息功能是吗？

**Comment by Qing-Novel** [comment]
> 嗯目前问题太多，不适合放出来用了，禁掉能缓解一些。
> 
> 后续什么时候能加回来我也不确定。

好吧。。。希望能早日回归这个功能

**Comment by Qing-Novel** [comment]
突然间想到，是不是接受频率的关系？我开的是1分钟间隔
