### ISSUE TITLE
关于表情的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#15]
表情下载后无法正常添加，且列表里没缩略图，且每次添加都需要重新下载，下载还很忙
请问表情可以预加载吗？预先做在软件里，或者第一次下完后面不要重新下载

https://github.com/user-attachments/assets/a232a4c7-68b5-4752-9234-95ff0b94169b

**Comment by Qing-Novel** [comment]
然后发emoji会显示几个问号，貌似手机网页版也有这个问题，请问作者这个问题可以修复或者优化吗？（电脑版网页没太注意，可能没这个问题）

**Comment by Qing-Novel** [comment]
> 表情有单独的缓存，完整下载一次就好，后续不会重新下载，而且有缩略图。 但是如果上次没下载完的话这次会接着下载。
> 
> 表情包的大小是10mb多一点，打包到软件里会导致安装包体积增大约一倍，而且后续更新表情会比较麻烦，所以不想直接塞进安装包里。
> 
> 目前算动态拉取的表情，先拉下来所有表情的链接，再对着表情链接下载，可能这部分功能有问题了。
> 
> ~我看一下吧，不好解的话要等两天，我坛庆活动也没做完~
> 
> emoji显示问号是因为服务器不支持，在网页端也是一样的，这个无能为力。

好的好的。那看样子是我手头的两台设备都没有完整下载表情（很奇怪，梯子也挂了都没用）

**Comment by realth000** [comment]
用这里的试试：
https://github.com/realth000/tsdm_client/actions/runs/11217157026

按说修好了，但我这还不太行，感觉网有问题。

你那边网页端上，表情都能加载出来嘛？

**Comment by Qing-Novel** [comment]
> 用这里的试试： https://github.com/realth000/tsdm_client/actions/runs/11217157026
> 
> 按说修好了，但我这还不太行，感觉网有问题。
> 
> 你那边网页端上，表情都能加载出来嘛？

我试试。其实别人发的表情可以看到的，单纯我发不了罢了。。。

**Comment by Qing-Novel** [comment]
> 用这里的试试： https://github.com/realth000/tsdm_client/actions/runs/11217157026
> 
> 按说修好了，但我这还不太行，感觉网有问题。
> 
> 你那边网页端上，表情都能加载出来嘛？

不对啊佬，莫得apk啊
![Screenshot_20241007_220430_com huawei browser](https://github.com/user-attachments/assets/c3a39da2-2684-4959-9a3e-c513cde150ff)

**Comment by realth000** [comment]
稍等等，还在编译。

是说编辑器里能都加载出来不，很多分组，我这有一部分不行。

**Comment by Qing-Novel** [comment]
> 稍等等，还在编译。
> 
> 是说编辑器里能都加载出来不，很多分组，我这有一部分不行。

呃我去看看

**Comment by Qing-Novel** [comment]
目前的版本死活加载不出来表情列表了XD等佬新版本上了我再试试

**Comment by Qing-Novel** [comment]
> 用这里的试试： https://github.com/realth000/tsdm_client/actions/runs/11217157026
> 
> 按说修好了，但我这还不太行，感觉网有问题。
> 
> 你那边网页端上，表情都能加载出来嘛？

我俩设备分别测试的：一个挂梯子一个不挂，挂梯子的开的早，加载完了，13种表情都在，没开梯子的开的晚，还在下

**Comment by Qing-Novel** [comment]
有时候会这样。。。
![Screenshot_20241007_223527_kzs th000 tsdm_client](https://github.com/user-attachments/assets/62c3894e-ec86-4ed6-ac7d-2abe3e7f637e)

**Comment by Qing-Novel** [comment]
> 有时候会这样。。。 ![Screenshot_20241007_223527_kzs th000 tsdm_client](https://private-user-images.githubusercontent.com/136884931/374213667-62c3894e-ec86-4ed6-ac7d-2abe3e7f637e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTIwNDYsIm5iZiI6MTcyODMxMTc0NiwicGF0aCI6Ii8xMzY4ODQ5MzEvMzc0MjEzNjY3LTYyYzM4OTRlLWVjODYtNGVkNi1hYzdkLTJhYmUzZTdmNjM3ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNDM1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzJkNDIzZGQ5ZGQzYzRiMTVjN2VmMzA2MDY5ODM1OGRlYTRkNGE2OTcyZTRlMjc0ZTZiOGU1NDRhMGNjYTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KNVseBysUWQjjdcVtsmCadEqYbzJlvnAWdIZTh5uqcs)

这种时候最少也得重新打开表情列表，有时候还得重新打开帖子才会显示表情

**Comment by Qing-Novel** [comment]
必须挂梯子才能下，不挂速度300k都没有，挂了可以2mb上下

**Comment by Qing-Novel** [comment]
20+MB还给我彪了好几秒才下完XD

**Comment by Qing-Novel** [comment]
问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。

**Comment by realth000** [comment]
> 20+MB还给我彪了好几秒才下完XD

手机开魔法的话，流量统计是翻倍的，我这里也是。

总大小应该是11mb多一点。

如果实在难下载的话，不行就放到安装包里了，后续也不更新了

**Comment by Qing-Novel** [comment]
> > 20+MB还给我彪了好几秒才下完XD
> 
> 手机开魔法的话，流量统计是翻倍的，我这里也是。
> 
> 总大小应该是11mb多一点。
> 
> 如果实在难下载的话，不行就放到安装包里了，后续也不更新了

话说tsdm更新过表情吗？要是没更新过我觉得直接做到安装包里得了，这下载实在是麻烦说实话。。。毕竟肯定会有人不用梯子用作者的软件。或者作者代理功能加个粘贴订阅链接功能也行XD

**Comment by realth000** [comment]
> 问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。

是做的类似flutter的logo，没有用默认工程的logo，默认是100%的flutter

**Comment by realth000** [comment]
> > > 20+MB还给我彪了好几秒才下完XD
> > 
> > 手机开魔法的话，流量统计是翻倍的，我这里也是。
> > 
> > 总大小应该是11mb多一点。
> > 
> > 如果实在难下载的话，不行就放到安装包里了，后续也不更新了
> 
> 话说tsdm更新过表情吗？要是没更新过我觉得直接做到安装包里得了，这下载实在是麻烦说实话。。。毕竟肯定会有人不用梯子用作者的软件。或者作者代理功能加个粘贴订阅链接功能也行XD

不清楚是否更新过，写死风险大，但要是难以下载的话还是要写死，哪怕安装包会增大10mb。

这两天再观察一下，之前下载还比较流畅

**Comment by Qing-Novel** [comment]
> > 问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。
> 
> 是做的类似flutter的logo，没有用默认工程的logo，默认是100%的flutter

好的好的。

**Comment by Qing-Novel** [comment]
> > > > 20+MB还给我彪了好几秒才下完XD
> > > 
> > > 
> > > 手机开魔法的话，流量统计是翻倍的，我这里也是。
> > > 总大小应该是11mb多一点。
> > > 如果实在难下载的话，不行就放到安装包里了，后续也不更新了
> > 
> > 
> > 话说tsdm更新过表情吗？要是没更新过我觉得直接做到安装包里得了，这下载实在是麻烦说实话。。。毕竟肯定会有人不用梯子用作者的软件。或者作者代理功能加个粘贴订阅链接功能也行XD
> 
> 不清楚是否更新过，写死风险大，但要是难以下载的话还是要写死，哪怕安装包会增大10mb。
> 
> 这两天再观察一下，之前下载还比较流畅

好的好的

**Comment by Qing-Novel** [comment]
> > 问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。
> 
> 是做的类似flutter的logo，没有用默认工程的logo，默认是100%的flutter

佬，我这边做手机主题的时候做了个您app的图标（顺便也做了svg图），您要不看看？仿官方图标
![Screenshot_20241008_184209](https://github.com/user-attachments/assets/cdd51e83-93df-440c-a2f3-5bf223be7d4f)

**Comment by realth000** [comment]
> > > 问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。
> > 
> > 是做的类似flutter的logo，没有用默认工程的logo，默认是100%的flutter
> 
> 佬，我这边做手机主题的时候做了个您app的图标（顺便也做了svg图），您要不看看？仿官方图标
> ![Screenshot_20241008_184209](https://github.com/user-attachments/assets/cdd51e83-93df-440c-a2f3-5bf223be7d4f)
> 

可爱捏（

可以提个pr，把https://github.com/realth000/tsdm_client/blob/master/assets%2Fimages%2Ftsdm_client.svg
换掉，
pr合了以后我再把图标都更新一下

**Comment by Qing-Novel** [comment]
> > > > 问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。
> > > 
> > > 
> > > 是做的类似flutter的logo，没有用默认工程的logo，默认是100%的flutter
> > 
> > 
> > 佬，我这边做手机主题的时候做了个您app的图标（顺便也做了svg图），您要不看看？仿官方图标
> > ![Screenshot_20241008_184209](https://private-user-images.githubusercontent.com/136884931/374522615-cdd51e83-93df-440c-a2f3-5bf223be7d4f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQ2NzUsIm5iZiI6MTcyODM5NDM3NSwicGF0aCI6Ii8xMzY4ODQ5MzEvMzc0NTIyNjE1LWNkZDUxZTgzLTkzZGYtNDQwYy1hMmYzLTViZjIyM2JlN2Q0Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMzMyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWUzZjcyODAyNTRmMmQ0NTBlOTA2OThmY2E5Yzg0ODA4YzlkMzMwNDgyMmIxOThjOGNkZWRhYzRiZWNlN2NhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2-g5YXiCLiiIwz2WA2ZHn9WznkTEugUZIgR_ZJrOL0o)
> 
> 可爱捏（
> 
> 可以提个pr，把https://github.com/realth000/tsdm_client/blob/master/assets%2Fimages%2Ftsdm_client.svg 换掉， pr合了以后我再把图标都更新一下

🤣从没提过pr，刚才翻了下，翻不到图标啊。。。我要不文件直接发这里？

**Comment by Qing-Novel** [comment]
> > > > > > 问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。
> > > > > 
> > > > > 
> > > > > 是做的类似flutter的logo，没有用默认工程的logo，默认是100%的flutter
> > > > 
> > > > 
> > > > 佬，我这边做手机主题的时候做了个您app的图标（顺便也做了svg图），您要不看看？仿官方图标
> > > > ![Screenshot_20241008_213723](https://private-user-images.githubusercontent.com/136884931/374581116-dd2124fc-aa99-4846-9d74-160f66f48cfd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTU3NzMsIm5iZiI6MTcyODM5NTQ3MywicGF0aCI6Ii8xMzY4ODQ5MzEvMzc0NTgxMTE2LWRkMjEyNGZjLWFhOTktNDg0Ni05ZDc0LTE2MGY2NmY0OGNmZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMzUxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDA3MGIxNzdhMGExNzliMzUwNmQ4NTdmZWFmZTZhZGNiMDI2YzQwYjEzYjg4ODdhZDY4N2YyMmZmNWQyMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tjJ2OD54IOKnFFS0bjUmXkVIW24kC986-nMaGrfsk6I)
> > > 
> > > 
> > > 可爱捏（
> > > 可以提个pr，把https://github.com/realth000/tsdm_client/blob/master/assets%2Fimages%2Ftsdm_client.svg 换掉， pr合了以后我再把图标都更新一下
> > 
> > 
> > 🤣从没提过pr，刚才翻了下，翻不到图标啊。。。我要不文件直接发这里？
> 
> 只要把assets/images/tsdm_client.svg这个文件换了就行，后面别的图标我自己更新
> 
> ~如果images里的都更新了最好不过~
> 
> 提pr可以看看网上的教程，其实不算难的，还是提不了的话直接发这里也行。

图全改了倒是不难，主要是不太会提。。。我查查教程看看，实在不行我发这里

**Comment by Qing-Novel** [comment]
> > > > > > 问个题外话，作者做的这个软件的图标不会是默认图标吧。。。怎么感觉跟flutter那么像啊。。
> > > > > 
> > > > > 
> > > > > 是做的类似flutter的logo，没有用默认工程的logo，默认是100%的flutter
> > > > 
> > > > 
> > > > 佬，我这边做手机主题的时候做了个您app的图标（顺便也做了svg图），您要不看看？仿官方图标
> > > > ![Screenshot_20241008_213723](https://private-user-images.githubusercontent.com/136884931/374581116-dd2124fc-aa99-4846-9d74-160f66f48cfd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTY0MzEsIm5iZiI6MTcyODM5NjEzMSwicGF0aCI6Ii8xMzY4ODQ5MzEvMzc0NTgxMTE2LWRkMjEyNGZjLWFhOTktNDg0Ni05ZDc0LTE2MGY2NmY0OGNmZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxNDAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmNkNjAxNDZiNDRkN2JmYzQxM2Y3MWZiYjdkOGU4NmY2NWMwYzcxMjRjNjIyMjhkNjVjNmE2NDcwNDk2MmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SsUmPrIrz83xsd_KI2uIeWl88tkPhETA-74zec1-zkA)
> > > 
> > > 
> > > 可爱捏（
> > > 可以提个pr，把https://github.com/realth000/tsdm_client/blob/master/assets%2Fimages%2Ftsdm_client.svg 换掉， pr合了以后我再把图标都更新一下
> > 
> > 
> > 🤣从没提过pr，刚才翻了下，翻不到图标啊。。。我要不文件直接发这里？
> 
> 只要把assets/images/tsdm_client.svg这个文件换了就行，后面别的图标我自己更新
> 
> ~如果images里的都更新了最好不过~
> 
> 提pr可以看看网上的教程，其实不算难的，还是提不了的话直接发这里也行。

佬看下，应该提了

**Comment by Qing-Novel** [comment]
> ok，合进来了

好的好的，其他的图在做，马上搞

**Comment by Qing-Novel** [comment]
> ok，合进来了

图片还是不太会🤣我发这里吧剩下的几张
[images.zip](https://github.com/user-attachments/files/17294718/images.zip)

**Comment by realth000** [comment]
图标合进来了，表情想了一下还是自带比较好，可以用这里的看看效果：

https://github.com/realth000/tsdm_client/actions/runs/11242570163

虽然说表情加载不出来的话，网站应该也访问不了（
但是下载11MB的东西还是有点逆天（
20多MB的体积还能接受吧

**Comment by realth000** [comment]
https://github.com/realth000/tsdm_client/actions/runs/11242868831

用这里的

**Comment by Qing-Novel** [comment]
> https://github.com/realth000/tsdm_client/actions/runs/11242868831
> 
> 用这里的

好的好的，我旧版本删了表情缓存后试试

**Comment by Qing-Novel** [comment]
> https://github.com/realth000/tsdm_client/actions/runs/11242868831
> 
> 用这里的

大问题没有了，有俩细节可能要改下，一个是加载表情时还是下载相关的字样，一个是清除缓存里还有表情相关的内容
![2024_10_09_073006107](https://github.com/user-attachments/assets/a74f40f6-2da0-4911-9ee8-95811fdfe552)
![2024_10_09_073011684](https://github.com/user-attachments/assets/76239326-a4e2-4d3e-84b2-d6e19a9bf5a5)

https://github.com/user-attachments/assets/8eef272c-b775-4c80-82b8-bf04f7b099ae

**Comment by realth000** [comment]
新提示加上了，忘了改。

缓存里要留着表情这一项，现在表情会在第一次点开编辑器的表情按钮的时候释放到数据目录里，可以被删除。
后续要做一个更新表情的功能，能下载新增的表情，这部分文件也要可以删除。

**Comment by Qing-Novel** [comment]
> 新提示加上了，忘了改。
> 
> 缓存里要留着表情这一项，现在表情会在第一次点开编辑器的表情按钮的时候释放到数据目录里，可以被删除。 后续要做一个更新表情的功能，能下载新增的表情，这部分文件也要可以删除。

好的好的，辛苦作者了。我这边后面要是使用中找不到啥新问题就坐等作者1.0.0的第9个版本了（太期待多账户和自动签到啦😁

**Comment by realth000** [comment]
翻译改掉了，下个版本会有，就先不出包了（

**Comment by Qing-Novel** [comment]
> 翻译改掉了，下个版本会有，就先不出包了（

好的
