### ISSUE TITLE
帖子字体颜色不变化

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#156]
可能是我不会使用，但是我这边打算给帖子里的内容改字体颜色时改不了，不知道怎么回事

https://github.com/user-attachments/assets/f1ab8c50-7c4c-40d4-92b1-9cd8d87f7b3a

**Comment by realth000** [comment]
用法没错，似乎只有移动端有这个问题

**Comment by Qing-Novel** [comment]
> 用法没错，似乎只有移动端有这个问题

啊这。。。。
突然发现怎么我总是能找到bugXD
然后具体用法是打字后选择字后点颜色还是先点颜色再打字？

**Comment by realth000** [comment]
这两种操作都行：不管是先选颜色后打字，还是先选中文字然后选颜色。

桌面端第一种方式有问题，暂时先用第二种凑合吧。

移动端的话，我很少在移动端打一些复杂的排版，所以一直没发现。

**Comment by Qing-Novel** [comment]
> 这两种操作都行：不管是先选颜色后打字，还是先选中文字然后选颜色。
> 
> 桌面端第一种方式有问题，暂时先用第二种凑合吧。
> 
> 移动端的话，我很少在移动端打一些复杂的排版，所以一直没发现。

原来如此。。。。
等佬下一个版本出来后我把这些功能都试一遍，看看还有啥问题XD

**Comment by Qing-Novel** [comment]
刚才试了下，这两个都有问题，之前只发现了调色盘图标功能的问题，油漆桶图标的功能也不能用
![Screenshot_20241231_093955](https://github.com/user-attachments/assets/b9b62a83-ec2f-43f7-bbe1-7d218c38bcdb)
调色盘的佬肯定修了，那油漆桶的佬有修吗？

**Comment by realth000** [comment]
都修了

**Comment by Qing-Novel** [comment]
好的

> 都修了
