### ISSUE TITLE
消息一直无限转圈

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#157]
不知道怎么回事突然这样，清除数据了没多长时间又这样了。。。

https://github.com/user-attachments/assets/71077838-e765-4117-ab95-0255633ca548

**Comment by realth000** [comment]
在设置 调试 里把日志导出了放上来

**Comment by Qing-Novel** [comment]
> 在设置 调试 里把日志导出了放上来

我先尝试重装看看，还不行我导日志

**Comment by realth000** [comment]
不用试了，接口有问题

**Comment by realth000** [comment]
等上游修复吧

**Comment by Qing-Novel** [comment]
好吧。。。。

**Comment by Qing-Novel** [comment]
😭我滴聊天记录啊

**Comment by Qing-Novel** [comment]
😭要是有备份功能就好了

**Comment by Qing-Novel** [comment]
对了佬，我点导出日志貌似没反应啊（只是想试一下）。。。

**Comment by realth000** [comment]
一般不要尝试重装，重装可能会掩盖问题，保存现场环境更重要一些。

/storage/emulated/0/Download这个目录存在吗？

**Comment by Qing-Novel** [comment]
> 一般不要尝试重装，重装可能会掩盖问题，保存现场环境更重要一些。
> 
> /storage/emulated/0/Download这个目录存在吗？

好吧。。。
这个目录在

**Comment by Qing-Novel** [comment]
![Screenshot_20241231_091102_bin mt plus canary](https://github.com/user-attachments/assets/229a3f90-cebe-4559-ac00-f0c546704725)

**Comment by realth000** [comment]
上游已恢复
