### ISSUE TITLE
关于头像的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#16]
我发现头像会反复加载，且网络不好的时候不加载只能显示默认头像（挂梯子会加载出来），可以像表情那样加载一次后续就不加载了，除非用户修改头像
还有avif格式头像会导致头像框变灰且不显示图片

**Comment by realth000** [comment]
> 我发现头像会反复加载，且网络不好的时候不加载只能显示默认头像（挂梯子会加载出来），可以像表情那样加载一次后续就不加载了，除非用户修改头像

正常下载好的头像有缓存，但安卓上缓存多的时候存在失效的问题，感觉是被系统清除了。

在考虑要不要把图片缓存也放到数据目录而不是缓存目录里，之前表情就因为时不时失效而放到数据目录里了，然后清缓存的时候可以选择不删除表情。
虽然这样不太规范。

如果放到数据里，还要加上自动清理功能，或者做一些更细致的分类，比如只删帖子里的图片，只删用户头像。

加载不出来头像的时候会用默认头像，这个默认头像在大部分地方没缓存（有的地方有），下次还会再尝试加载，后续会统一不缓存，防止失败一次就一直用默认头像。

头像和缓存的改进会放到1.0之后的版本里，1.0先不动这部分了，目前还没计划好怎么做。

**Comment by Qing-Novel** [comment]
> > 我发现头像会反复加载，且网络不好的时候不加载只能显示默认头像（挂梯子会加载出来），可以像表情那样加载一次后续就不加载了，除非用户修改头像
> 
> 正常下载好的头像有缓存，但安卓上缓存多的时候存在失效的问题，感觉是被系统清除了。
> 
> 在考虑要不要把图片缓存也放到数据目录而不是缓存目录里，之前表情就因为时不时失效而放到数据目录里了，然后清缓存的时候可以选择不删除表情。 虽然这样不太规范。
> 
> 如果放到数据里，还要加上自动清理功能，或者做一些更细致的分类，比如只删帖子里的图片，只删用户头像。
> 
> 加载不出来头像的时候会用默认头像，这个默认头像在大部分地方没缓存（有的地方有），下次还会再尝试加载，后续会统一不缓存，防止失败一次就一直用默认头像。
> 
> 头像和缓存的改进会放到1.0之后的版本里，1.0先不动这部分了，目前还没计划好怎么做。

好的好的

**Comment by realth000** [comment]
头像这个，目前计划包括以下几部分：

1. 缓存也放到数据目录，这样不会被系统清除。（可能只有安卓会这样做，其他平台还放在缓存区）~~我也要当恶龙了~~
2. 配套的会加上图片分类和定时清理，这样清缓存的时候可以选择只清除版区的/用户相关的/帖子内的图片，这几种图片按说持有的有效期并不同，像帖子里会有很多非常大的图片，大部分帖子也就看个一两次，可以尽快清理，而版区的封面图基本不会动，体积也小，可以设置个长一些的有效时间。
3. 会保留所有加载过的用户的头像，这样在一些展示用户信息但服务器没给头像的地方可以用缓存，比如主页下面那些置顶的帖子，还有通知里的。

这些改动会伴随着切换api同步进行，所以也要等等。

这次迁移涉及到的内容很多，要慢慢弄了。

**Comment by Qing-Novel** [comment]
> 头像这个，目前计划包括以下几部分：
> 
> 1. 缓存也放到数据目录，这样不会被系统清除。（可能只有安卓会这样做，其他平台还放在缓存区）~我也要当恶龙了~
> 2. 配套的会加上图片分类和定时清理，这样清缓存的时候可以选择只清除版区的/用户相关的/帖子内的图片，这几种图片按说持有的有效期并不同，像帖子里会有很多非常大的图片，大部分帖子也就看个一两次，可以尽快清理，而版区的封面图基本不会动，体积也小，可以设置个长一些的有效时间。
> 3. 会保留所有加载过的用户的头像，这样在一些展示用户信息但服务器没给头像的地方可以用缓存，比如主页下面那些置顶的帖子，还有通知里的。
> 
> 这些改动会伴随着切换api同步进行，所以也要等等。
> 
> 这次迁移涉及到的内容很多，要慢慢弄了。

好的
