### ISSUE TITLE
关于帖子图片的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#18]
https://github.com/user-attachments/assets/4e900ab9-c683-4271-ad64-041f7eeaa9fc

![Screenshot_20241009_130120_kzs th000 tsdm_client](https://github.com/user-attachments/assets/386fbc6c-9e6b-496a-a0fb-8ec19391b5e7)
查看图片的时候一直在闪，而且刚进入图片查看模式的时候图片排版上下不太居中，然后想问下佬可不可以加一个图片下载功能？

**Comment by realth000** [comment]
emm是~~懒得改的~~已知问题，在改了在改了

竖直居中不会做，后续会显示图片的相关信息。

下载的话，现在已经有复制图片链接的功能了，所以没想着加下载功能。
可以加上

**Comment by Qing-Novel** [comment]
> emm是~懒得改的~已知问题，在改了在改了
> 
> 竖直居中不会做，后续会显示图片的相关信息。
> 
> 下载的话，现在已经有复制图片链接的功能了，所以没想着加下载功能。 可以加上

好的好的XD
ps：佬有要到官方的api吗（搓手
