### ISSUE TITLE
关于最新主题的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#19]
帖子卡片里出现了代码
![Screenshot_20241010_160828_kzs th000 tsdm_client](https://github.com/user-attachments/assets/eb83a048-d372-4d2f-bf02-af3e0836ba94)

https://github.com/user-attachments/assets/912d175b-9ecd-46ef-b8bf-ee83311729af

**Comment by realth000** [comment]
消息里原本自带的，可以到网页端确认。

**Comment by Qing-Novel** [comment]
> 消息里原本自带的，可以到网页端确认。

好吧。主要是进帖子就没有了

**Comment by realth000** [comment]
> > 消息里原本自带的，可以到网页端确认。
> 
> 那个。。。佬。。。似乎没有啊网页端。。。
> ![Screenshot_20241010_183822_com huawei browser](https://github.com/user-attachments/assets/63e96cbe-110b-44d8-88ee-9efd857f30e8)
> ![Screenshot_20241010_183837_com huawei browser](https://github.com/user-attachments/assets/60d5f3c2-3c5c-4540-bb26-27adcf268769)
> ![Screenshot_20241010_183754_com huawei browser](https://github.com/user-attachments/assets/fe6acd35-ba77-4cd8-badc-f4ac91647696)
> ![Screenshot_20241010_183813_com huawei browser](https://github.com/user-attachments/assets/09498ef4-4793-4364-a693-5462e9185a59)
> 

hr就是分割线，你看第一张图里，表格上方有两个分割线。

**Comment by Qing-Novel** [comment]
> > > 消息里原本自带的，可以到网页端确认。
> > 
> > 
> > 那个。。。佬。。。似乎没有啊网页端。。。
> > ![Screenshot_20241010_183822_com huawei browser](https://private-user-images.githubusercontent.com/136884931/375340191-63e96cbe-110b-44d8-88ee-9efd857f30e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTczNDMsIm5iZiI6MTcyODU1NzA0MywicGF0aCI6Ii8xMzY4ODQ5MzEvMzc1MzQwMTkxLTYzZTk2Y2JlLTExMGItNDRkOC04OGVlLTllZmQ4NTdmMzBlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMDQ0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzVhMGU3MmM2YzkyZGViMDFlYjhmYTMzNDFmMjkwYjk2YWFhNzEwN2NkY2I1YTVlYTEwNGE0NGY2MmM4NzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bc4Ero1p2NUIGVemrIcEvfRPkVmGQhPADZKXMJELxTM)
> > ![Screenshot_20241010_183837_com huawei browser](https://private-user-images.githubusercontent.com/136884931/375340199-60d5f3c2-3c5c-4540-bb26-27adcf268769.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTczNDMsIm5iZiI6MTcyODU1NzA0MywicGF0aCI6Ii8xMzY4ODQ5MzEvMzc1MzQwMTk5LTYwZDVmM2MyLTNjNWMtNDU0MC1iYjI2LTI3YWRjZjI2ODc2OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMDQ0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGI4ZjhhY2IwOWNkYWE1NTFkOGEzZDcyYmM0NjRhMjIxMGFmNjA3ZWMzZjFjNDQ2MjYyYWM5Y2Y3NjI2ZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.REpHcldjMKjNW3QAnR25RF17zGZ0dy5C46n0xFotpbk)
> > ![Screenshot_20241010_183754_com huawei browser](https://private-user-images.githubusercontent.com/136884931/375340220-fe6acd35-ba77-4cd8-badc-f4ac91647696.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTczNDMsIm5iZiI6MTcyODU1NzA0MywicGF0aCI6Ii8xMzY4ODQ5MzEvMzc1MzQwMjIwLWZlNmFjZDM1LWJhNzctNGNkOC1iYWRjLWY0YWM5MTY0NzY5Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMDQ0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTExMWQxYTZmYWM1NzFkZmNkM2M2NGIxYzZiOGU4Mjc4NTQ1NjRkYmM5NDJjNWMxYTMyZTcyZTk0MWUyMjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BPspG8-_xlG78mdyyYFNnGROfDTCHJcZe7Z209eF0AQ)
> > ![Screenshot_20241010_183813_com huawei browser](https://private-user-images.githubusercontent.com/136884931/375340237-09498ef4-4793-4364-a693-5462e9185a59.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTczNDMsIm5iZiI6MTcyODU1NzA0MywicGF0aCI6Ii8xMzY4ODQ5MzEvMzc1MzQwMjM3LTA5NDk4ZWY0LTQ3OTMtNDM2NC1hNjkzLTU0NjJlOTE4NWE1OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMDQ0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWJlMzEzMDExODU5Y2IwYTYwYWFiY2JjMTY3MmU2YzE2OTc4MGRkZjRkODc2YTI5YTczYjEyNjljMjU2ZDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aIO9SBryJ7h-C6r-6Aox4etrPgueTXb86QTZ1L-Q5oo)
> 
> hr就是分割线，你看第一张图里，表格上方有两个分割线。

好的好的。不过佬，这个可以优化下吗，像这种效果代码卡片里就不显示这种

**Comment by Qing-Novel** [comment]
> 代码卡片里是源代码，不会渲染出样式。
> 
> 做起来比较麻烦，要去匹配用户输入的内容，而且消息可能会截断代码，不完整的代码渲染出来会有问题。

emmmmmm个人是希望能优化下，因为有代码这看起来多少有些别扭，但要是实现起来太麻烦就。。。

**Comment by Qing-Novel** [comment]
> 代码卡片里是源代码，不会渲染出样式。
> 
> 做起来比较麻烦，要去匹配用户输入的内容，而且消息可能会截断代码，不完整的代码渲染出来会有问题。

或者就像官方那样显示标题不显示正文得了

**Comment by realth000** [comment]
目前的做法是尽量保持网页端常用的功能，信息不比网页端少。

消息这部分后面可能重构，目前有很多类型的消息解析不到，可能会做成更原始的外观，难看一点，但不会少消息。

外观这个没有办法，现在服务器返回来的引用别人内容的回复渲染以后有删除线漏出来的问题，原因就是前面说到的截断。
像你图里举的例子，渲染完只有表格第一行，后面没闭合。前面还有上一个表格的闭合标签，不知道完整的是什么样子。

所以这部分更倾向于保持原样，把信息展示出来。

**Comment by Qing-Novel** [comment]
> 目前的做法是尽量保持网页端常用的功能，信息不比网页端少。
> 
> 消息这部分后面可能重构，目前有很多类型的消息解析不到，可能会做成更原始的外观，难看一点，但不会少消息。
> 
> 外观这个没有办法，现在服务器返回来的引用别人内容的回复渲染以后有删除线漏出来的问题，原因就是前面说到的截断。 像你图里举的例子，渲染完只有表格第一行，后面没闭合。前面还有上一个表格的闭合标签，不知道完整的是什么样子。
> 
> 所以这部分更倾向于保持原样，把信息展示出来。

好吧

**Comment by realth000** [comment]
这部分暂时不做改动，先关掉了
