### ISSUE TITLE
关于消息提示疑似异常的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#23]
https://github.com/user-attachments/assets/f52edfdb-d00a-45c3-a8fd-0d62e5f75769

私人消息不显示红点了（不知道帖子回复是不是也这样）

**Comment by realth000** [comment]
有时候没有新短消息提示，网页端就如此，具体原因不明，可以到网页端确认。

**Comment by Qing-Novel** [comment]
> 有时候没有新短消息提示，网页端就如此，具体原因不明，可以到网页端确认。

好的

**Comment by Qing-Novel** [comment]
是不是拿到api才能彻底解决这个问题啊佬？

**Comment by realth000** [comment]
跟拉取通知的方式应该没有关系，可能要等一等才有通知，看服务器给的什么数据了，偶现的。等后面换成api以后看看有没有问题吧，有问题也没办法（

提醒有时候会不显示未读提醒，这个是已知的，现在的实现方式有问题，换成api以后会好。

**Comment by Qing-Novel** [comment]
> 跟拉取通知的方式应该没有关系，可能要等一等才有通知，看服务器给的什么数据了，偶现的。等后面换成api以后看看有没有问题吧，有问题也没办法（
> 
> 提醒有时候会不显示未读提醒，这个是已知的，现在的实现方式有问题，换成api以后会好。

好的
