### ISSUE TITLE
关于代理功能的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#24]
![Screenshot_20241013_140144_kzs th000 tsdm_client](https://github.com/user-attachments/assets/a3ac4a46-56fc-4f42-8947-9672c30b468a)
佬能不能给代理功能加一个可以使用订阅链接的功能啊，这样我每次开软件就不用开梯子了（有时候不开梯子图片头像加载不出来）

**Comment by realth000** [comment]
不开的话只能自带代理功能，这个是肯定不会做的…

**Comment by Qing-Novel** [comment]
> 不开的话只能自带代理功能，这个是肯定不会做的…

好的
