### ISSUE TITLE
关于简繁体字切换功能的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#25]
能不能加一个简繁体切换的功能？因为有的用户发文是用繁体字发的，看起来很麻烦

**Comment by Qing-Novel** [comment]
不过可能跟等级有关系吧。。。昨天我是片翼天使LV2，发完领糖贴变成水天使了

**Comment by realth000** [comment]
有计划加翻译功能，readme里提到了，但是这部分功能优先级很低，因为做起来比较麻烦，效果也不好保证。

~~主要我也用不到~~

**Comment by Qing-Novel** [comment]
> 有计划加翻译功能，readme里提到了，但是这部分功能优先级很低，因为做起来比较麻烦，效果也不好保证。
> 
> ~主要我也用不到~

好的

**Comment by Qing-Novel** [comment]
> readme里功能已经列了，这个issue先关了吧。 其实短期内实现不了，我在想要不要砍掉（

好的
好家伙，别砍啊，毕竟有用繁体的人在用啊

**Comment by realth000** [comment]
做起来麻烦而且效果不好的话就得考虑砍掉了，人家用的翻译不一定是免费的，可能是各种付费的，想接入也接入不了。

~~而且我用不上~~

**Comment by Qing-Novel** [comment]
> 做起来麻烦而且效果不好的话就得考虑砍掉了，人家用的翻译不一定是免费的，可能是各种付费的，想接入也接入不了。
> 
> ~而且我用不上~

emmmm
唉。。。
主要是有的繁体字是真看不懂啊，天使动漫用户有用繁体字的用户，而且还有一定数量
嘛，最终解释权自然还是佬的😁
