### ISSUE TITLE
关于我的帖子搜索的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#27]
希望能在我的帖子模块加一个搜索，发的帖子有一定数量，想找特定的帖子得翻半天，不太方便
![Screenshot_20241015_231935_kzs th000 tsdm_client](https://github.com/user-attachments/assets/a624ce68-7c0a-4dab-9784-c45928c853cc)

**Comment by realth000** [comment]
能加，但不会有正常搜索那样好使，因为没有直接的搜索接口，只能在已经加载的这部分历史记录里本地搜索。

所以操作下来是：

1. 加载了一页历史记录，搜索没搜到
2. 再加载一页，在两页里搜索，没搜到
2. 再加载一页，在三页里搜索，没搜到

以此类推

这个功能如果做成这样子的话，和没有也差不多，找不到的帖子那肯定不是前几页一眼能看见的，意义不大。

如果是帖子有评分（尤其是ww/tsb）的话，建议到积分记录里找。

**Comment by Qing-Novel** [comment]
> 能加，但不会有正常搜索那样好使，因为没有直接的搜索接口，只能在已经加载的这部分历史记录里本地搜索。
> 
> 所以操作下来是：
> 
> 1. 加载了一页历史记录，搜索没搜到
> 2. 再加载一页，在两页里搜索，没搜到
> 3. 再加载一页，在三页里搜索，没搜到
> 
> 以此类推
> 
> 这个功能如果做成这样子的话，和没有也差不多，找不到的帖子那肯定不是前几页一眼能看见的，意义不大。
> 
> 如果是帖子有评分（尤其是ww/tsb）的话，建议到积分记录里找。

emmmmm有点可惜了，要是有接口就好了

**Comment by realth000** [comment]
先关掉了，目前没有办法（

或者去搜索里输入自己uid搜索

**Comment by Qing-Novel** [comment]
> 先关掉了，目前没有办法（
> 
> 或者去搜索里输入自己uid搜索

好的好的

**Comment by Qing-Novel** [comment]
> 先关掉了，目前没有办法（
> 
> 或者去搜索里输入自己uid搜索

佬，那可不可以做成表面是我的发帖的搜索，其实是普通搜索但是默认填写了用户的uid，然后用户输入关键词在搜索不就达成我的发帖的搜索了吗？

**Comment by realth000** [comment]
数据不一样，普通搜索里少一些帖子的信息，也搜不到草稿，某些分区也搜不到

**Comment by Qing-Novel** [comment]
> 数据不一样，普通搜索里少一些帖子的信息，也搜不到草稿，某些分区也搜不到

搜不到草稿还可以。。。不过搜不到一些分区和帖子有点伤。。。

**Comment by Qing-Novel** [comment]
> 数据不一样，普通搜索里少一些帖子的信息，也搜不到草稿，某些分区也搜不到

佬我看网页端个人资料里有一个 搜索TA发表过的主题 ，这个应该可以都搜到吧。。

**Comment by realth000** [comment]
> > 数据不一样，普通搜索里少一些帖子的信息，也搜不到草稿，某些分区也搜不到
> 
> 佬我看网页端个人资料里有一个 搜索TA发表过的主题 ，这个应该可以都搜到吧。。

那个就是搜索的时候指定uid

**Comment by Qing-Novel** [comment]
> > > 数据不一样，普通搜索里少一些帖子的信息，也搜不到草稿，某些分区也搜不到
> > 
> > 
> > 佬我看网页端个人资料里有一个 搜索TA发表过的主题 ，这个应该可以都搜到吧。。
> 
> 那个就是搜索的时候指定uid

emmmm好吧

**Comment by Qing-Novel** [comment]
> 数据不一样，普通搜索里少一些帖子的信息，也搜不到草稿，某些分区也搜不到
![360截图20241109162144](https://github.com/user-attachments/assets/c9ab4b94-5a87-48be-8b14-ef2487beafed)

![360截图20241109162136](https://github.com/user-attachments/assets/94d729b4-94bf-4c57-802a-9f70195de8cf)
佬，这里的话就能看到用户发的所有的帖子吧

**Comment by realth000** [comment]
这里就是现在的数据来源，里面只能一页一页加载

**Comment by Qing-Novel** [comment]
> 这里就是现在的数据来源，里面只能一页一页加载

原来如此。。。。
