### ISSUE TITLE
关于发帖图片尺寸代码的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#28]
貌似app里图片设置的尺寸没使用，不管设置的尺寸是多少都按照屏幕规格显示
![Screenshot_20241015_232312_kzs th000 tsdm_client](https://github.com/user-attachments/assets/3166c378-693b-47ad-93cf-844ca7d8940d)
![Screenshot_20241015_232324_kzs th000 tsdm_client](https://github.com/user-attachments/assets/e681a116-09a5-41fb-8f4d-aa0e96a631cc)
![Screenshot_20241015_232336_com huawei browser](https://github.com/user-attachments/assets/cf3e7838-5ced-4297-b2bb-b0345331ccc9)

**Comment by realth000** [comment]
发帖的时候设置的图片大小只限制了bbcode里写着的图片大小，因为各版区附图时都有这个要求。

但是从网页内容渲染回来的时候并没有遵从图片大小，目前确实是这样，周末我改一下吧。

**Comment by Qing-Novel** [comment]
> 发帖的时候设置的图片大小只限制了bbcode里写着的图片大小，因为各版区附图时都有这个要求。
> 
> 但是从网页内容渲染回来的时候并没有遵从图片大小，目前确实是这样，周末我改一下吧。

好的好的

**Comment by realth000** [comment]
已在 0436ab3 中修复
