### ISSUE TITLE
关于网站其他功能的询问

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#29]
请问天使动漫网站比如银行、宠物系统、勋章和第二称号有制作的计划吗？

**Comment by realth000** [comment]
银行没用过，如果好做的话会做。

宠物系统之前想做，但这部分比较难做，东西很多，比较复杂，做也比较靠后了。

勋章和牌子是说设置显示，还是购买？前者的话没有看过，应该不算难做，后者的话比较危险，不好测。

这些算在考虑中，比起这些还有优先级更高的功能要做。

**Comment by Qing-Novel** [comment]
> 银行没用过，如果好做的话会做。
> 
> 宠物系统之前想做，但这部分比较难做，东西很多，比较复杂，做也比较靠后了。
> 
> 勋章和牌子是说设置显示，还是购买？前者的话没有看过，应该不算难做，后者的话比较危险，不好测。
> 
> 这些算在考虑中，比起这些还有优先级更高的功能要做。

好的好的。勋章和牌子显示是想要的，买可以的话也想要，如果做不了能不能套个网站来实现买这个功能呢？

**Comment by realth000** [comment]
勋章/牌子的显示具体说的是什么？

我刚才说的是可以设置勋章顺序、设置显示哪个牌子，这种，这个功能会后期做。

如果是帖子和用户资料里显示当前佩戴的勋章/牌子的话，1.0版本会上这个功能，roadmap里有。

**Comment by Qing-Novel** [comment]
> 勋章/牌子的显示具体说的是什么？
> 
> 我刚才说的是可以设置勋章顺序、设置显示哪个牌子，这种，这个功能会后期做。
> 
> 如果是帖子和用户资料里显示当前佩戴的勋章/牌子的话，1.0版本会上这个功能，roadmap里有。

是指显示。坐等大佬更新了。购买的话您看看能不能套个网页，网页里操作？

**Comment by realth000** [comment]
先关了吧，这里面讨论的东西太多，等后面慢慢加，目前的计划是先把底层能迁移到api的都迁移了，然后再考虑扩展功能

**Comment by Qing-Novel** [comment]
好的
