### ISSUE TITLE
关于天使动漫在线动漫的询问

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#30]
请问佬之后会给天使动漫的在线动漫做个专门的入口吗？
![Screenshot_20241016_150143_kzs th000 tsdm_client](https://github.com/user-attachments/assets/82c63712-7f1d-4f2d-9270-20f59ac36d97)

**Comment by realth000** [comment]
不会做，这个功能太远了（

**Comment by Qing-Novel** [comment]
> 不会做，这个功能太远了（

好的好的
