### ISSUE TITLE
关于消息提醒的排序问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#31]
现在1.0.0-alpha.9的排序是正序，请问佬可以改成之前的倒序吗？

**Comment by Qing-Novel** [comment]
刚才我用小号测试了下，发现是之前的数据是正序，新的数据还是倒序。。。佬这个可以修吗？

**Comment by realth000** [comment]
没注意排序（

可以先用这里的：

https://github.com/realth000/tsdm_client/actions/runs/11416211430

**Comment by Qing-Novel** [comment]
> 没注意排序（
> 
> 可以先用这里的：
> 
> https://github.com/realth000/tsdm_client/actions/runs/11416211430

好的好的
