### ISSUE TITLE
关于之前的消息提醒的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#33]
8之前的版本是可以看到以前的消息提醒的（官方app也是），9这个版本私人消息和公共消息都看不到安装前已有的消息了

**Comment by Qing-Novel** [comment]
https://github.com/user-attachments/assets/20dbdfe5-d19b-4921-b271-63a2d44daef6

**Comment by Qing-Novel** [comment]
😂我试着找了一个没装官方app的设备装官方app，结果也没加载出来。。。
不过网页端能看到。。。。
这个看样子也不算是问题了。。。不过还是希望佬能加下之前的消息提醒（加不了就算了，毕竟官方app也这样）

**Comment by realth000** [comment]
现在和官方app一样，只会拉取最近三天的消息，然后存到数据里。
再之前的估计是不行。

**Comment by Qing-Novel** [comment]
> 现在和官方app一样，只会拉取最近三天的消息，然后存到数据里。 再之前的估计是不行。

好吧。。。多少有些遗憾了
