### ISSUE TITLE
关于手机端软件名的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#35]
![Screenshot_20241019_123135_com huawei android launcher](https://github.com/user-attachments/assets/d28d6318-a34a-4a03-89a5-d234fd544f05)
手机端多任务界面软件名显示为天使动漫客户端，因为名字有点长导致无法显示完整，请问佬可以改成天使动漫吗？

**Comment by realth000** [comment]
可以改的，我看看怎么改吧。

想把i18n也加上

**Comment by Qing-Novel** [comment]
> 可以改的，我看看怎么改吧。
> 
> 想把i18n也加上

好的，辛苦佬了
话说i18n是啥？

**Comment by realth000** [comment]
就是软件的名字也加上翻译，在中文系统上显示中文，在英文系统上显示英文。

还不清楚怎么做，不过肯定不难做

**Comment by Qing-Novel** [comment]
> 就是软件的名字也加上翻译，在中文系统上显示中文，在英文系统上显示英文。
> 
> 还不清楚怎么做，不过肯定不难做

好的，辛苦佬了
