### ISSUE TITLE
关于图片显示的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#36]
新版本图片可以读取尺寸代码显示了，但是文字和图片之间出现了留白（已确认代码模式下没有空行），猜测可能文字和图片的显示还是按照图片长度铺满屏幕来计算的

https://github.com/user-attachments/assets/24f33071-2b71-41a3-8dc6-8cf0f8e6fbaf

**Comment by Qing-Novel** [comment]
确认了，跟图片的尺寸代码有关

https://github.com/user-attachments/assets/de449253-adf2-4af6-8c47-fcdebb58e513

**Comment by realth000** [comment]
修好了

https://github.com/realth000/tsdm_client/actions/runs/11423643393

**Comment by Qing-Novel** [comment]
> 修好了
> 
> https://github.com/realth000/tsdm_client/actions/runs/11423643393

好的，辛苦佬了
