### ISSUE TITLE
关于贴内回复显示的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#38]
之前的版本就有这个情况：帖子内回复完后不显示内容，需要右上角点击刷新才能显示，希望能改进下，发完回复不用自己点刷新就能看到内容

https://github.com/user-attachments/assets/bf76f7ff-69ed-4368-b319-ae9e4b2d0d89

**Comment by Qing-Novel** [comment]
像这种需要刷新才会显示新内容的地方挺多的，比如个人主页，之前打开过个人主页的话，比如卖出了新主题或者回复内容，天使币、威望的变化在重新打开个人主页后如果不刷新是不会变化的

**Comment by realth000** [comment]
分两种：

1. 帖子里回复和评分这种情况我是觉得没必要做，因为网页上返还回来的并不准确，比如水区回复楼层会折叠，多次回复会显示多个同一楼层，在app里用容易出问题，为了后续加载页面以后显示得准确，要考虑提前把这些标记成脏数据，逻辑很麻烦。
2. 个人主页没有好的优化方法，待我想想吧（

**Comment by Qing-Novel** [comment]
> 分两种：
> 
> 1. 帖子里回复和评分这种情况我是觉得没必要做，因为网页上返还回来的并不准确，比如水区回复楼层会折叠，多次回复会显示多个同一楼层，在app里用容易出问题，为了后续加载页面以后显示得准确，要考虑提前把这些标记成脏数据，逻辑很麻烦。
> 2. 个人主页没有好的优化方法，待我想想吧（

1我个人觉得就发完内容后自动刷新下页面就行，2麻烦佬了

**Comment by realth000** [comment]
> > 分两种：
> > 
> > 1. 帖子里回复和评分这种情况我是觉得没必要做，因为网页上返还回来的并不准确，比如水区回复楼层会折叠，多次回复会显示多个同一楼层，在app里用容易出问题，为了后续加载页面以后显示得准确，要考虑提前把这些标记成脏数据，逻辑很麻烦。
> > 2. 个人主页没有好的优化方法，待我想想吧（
> 
> 1我个人觉得就发完内容后自动刷新下页面就行，2麻烦佬了

1. 要只刷当前页，然后用新数据替换掉之前的。
2. 还有一种情况，帖子里的楼层刚好铺满一页，新回复会发到下一页，这时候就不能把当前页刷掉了。后续再拉取新页数的时候要从新回复这页开始拉。
3. 还有一些情况，比如现在一共3页，从第2页开始回复，回复的内容会出现在第三页上，回复以后按说看不到新回复才对。
4. 又或者我是倒序浏览的帖子（我个人一直开的倒序看），新回复应该出现在帖子最上方，但现在的布局没法往帖子上下两头都加数据（这个问题在计划中，但暂时不会改）。
5. 如果要做刷新的话，刷新期间界面上肯定要做提示，这时候肯定不能让做翻页或者回复之类的操作，感觉不太行。

要考虑的东西挺多的，目前开发重点没在帖子回复刷新的浏览体验上，等后面再改进吧（

下一步是之前说的多用户和自动签到，还有编辑器的改进，编辑器目前很多格式还不支持。

**Comment by Qing-Novel** [comment]
> > > 分两种：
> > > 
> > > 1. 帖子里回复和评分这种情况我是觉得没必要做，因为网页上返还回来的并不准确，比如水区回复楼层会折叠，多次回复会显示多个同一楼层，在app里用容易出问题，为了后续加载页面以后显示得准确，要考虑提前把这些标记成脏数据，逻辑很麻烦。
> > > 2. 个人主页没有好的优化方法，待我想想吧（
> > 
> > 
> > 1我个人觉得就发完内容后自动刷新下页面就行，2麻烦佬了
> 
> 1. 要只刷当前页，然后用新数据替换掉之前的。
> 2. 还有一种情况，帖子里的楼层刚好铺满一页，新回复会发到下一页，这时候就不能把当前页刷掉了。后续再拉取新页数的时候要从新回复这页开始拉。
> 3. 还有一些情况，比如现在一共3页，从第2页开始回复，回复的内容会出现在第三页上，回复以后按说看不到新回复才对。
> 4. 又或者我是倒序浏览的帖子（我个人一直开的倒序看），新回复应该出现在帖子最上方，但现在的布局没法往帖子上下两头都加数据（这个问题在计划中，但暂时不会改）。
> 5. 如果要做刷新的话，刷新期间界面上肯定要做提示，这时候肯定不能让做翻页或者回复之类的操作，感觉不太行。
> 
> 要考虑的东西挺多的，目前开发重点没在帖子回复刷新的浏览体验上，等后面再改进吧（
> 
> 下一步是之前说的多用户和自动签到，还有编辑器的改进，编辑器目前很多格式还不支持。

好的，辛苦佬了

**Comment by realth000** [comment]
这个issue先关了吧，现在看来很不好做，效果不会多好，还有有bug

**Comment by Qing-Novel** [comment]
> 这个issue先关了吧，现在看来很不好做，效果不会多好，还有有bug

好的
