### ISSUE TITLE
关于图片放大查看的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#39]
请问佬在查看图片详情的时候能增加个允许放大的功能吗，比如视频里的这个图字很小看不清楚，但是现在的版本一放大松手后就回去了

https://github.com/user-attachments/assets/08ba9fd0-94d8-4b38-b681-5fbe2094c72a

ps：能否加个图片下载的功能啊

**Comment by realth000** [comment]
可以在这个界面再点一下图片，就全屏了（

**Comment by Qing-Novel** [comment]
> 可以在这个界面再点一下图片，就全屏了（

好的，佬要不写个提示，这真不知道啊🤣
点后就可以双指放大了

**Comment by realth000** [comment]
这部分做得不太满意，因为用的第三方控件，需要跳转一下页面。

后续我改进一下吧。

**Comment by Qing-Novel** [comment]
> 这部分做得不太满意，因为用的第三方控件，需要跳转一下页面。
> 
> 后续我改进一下吧。

好的
