### ISSUE TITLE
关于个人主页右上角四个功能按键的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#42]
![IMG_20241020_171354](https://github.com/user-attachments/assets/b9be5d9f-b935-4dd7-a443-fb71b54d0dbb)
![Collage_20241020_171330](https://github.com/user-attachments/assets/d4983968-828b-4747-aa05-a5d31fdf52a8)
佬，由于头像的设置问题，有时候会看不清楚个人主页右上角这四个按键，要不给这四个按键加个圆形背景？然后跟随系统变化夜间/白天模式，这样也看得清楚

**Comment by Qing-Novel** [comment]
整了三个效果，您看下（第二个和第三个的区别只是左上角返回按键有否圆形背景
![Collage_20241020_173412](https://github.com/user-attachments/assets/ec188b08-198d-4a94-b029-127c70c488b3)
![Collage_20241020_173427](https://github.com/user-attachments/assets/9e4da31d-7a29-43ac-a3ce-f87b3bb281ed)
![Collage_20241020_173443](https://github.com/user-attachments/assets/451260b6-6bb7-4c7d-b32b-3f48082dd38d)

**Comment by realth000** [comment]
是的，按照material design规范，背景是图片的按钮应该带背景色。

**Comment by Qing-Novel** [comment]
> 是的，按照material design规范，背景是图片的按钮应该带背景色。

带背景色吧，要不然有的按键有可能看不清楚

**Comment by realth000** [comment]
暂时把背景去掉了

**Comment by Qing-Novel** [comment]
> 是的，按照material design规范，背景是图片的按钮应该带背景色。

佬，之后主页的背景还会做回来吗？

**Comment by realth000** [comment]
应该会，但不一定是现在这个样子了

**Comment by Qing-Novel** [comment]
> 应该会，但不一定是现在这个样子了

好的好的。坐等了（
XD感觉天使动漫官方可以直接用佬的软件了
话说web app后面真的不搞了吗，感觉可以整个然后替换掉天使动漫官方网页的手机版网页了

**Comment by Qing-Novel** [comment]
顺带ios用户中不会整签名的用户也能用了

**Comment by realth000** [comment]
web支持很困难，要替换很多逻辑甚至依赖，而且还有跨域之类的问题，上次试了效果并不好。

这个web可能和你想的不一样，它需要有一个服务器去跑，然后其他设备才能走浏览器访问。
除非打算在家里的路由器之类的设备上跑一个，然后手机去访问。

加上flutter web对浏览器要求高，还有第一屏加载慢等等问题。
另外你想用平常的web插件的话，像ad block和油猴，应该都用不了，因为它窗口是拿canvas画出来的，不是一层套一层的html节点，这些插件都找不到页面上的元素。

**Comment by Qing-Novel** [comment]
> web支持很困难，要替换很多逻辑甚至依赖，而且还有跨域之类的问题，上次试了效果并不好。
> 
> 这个web可能和你想的不一样，它需要有一个服务器去跑，然后其他设备才能走浏览器访问。 除非打算在家里的路由器之类的设备上跑一个，然后手机去访问。
> 
> 加上flutter web对浏览器要求高，还有第一屏加载慢等等问题。 另外你想用平常的web插件的话，像ad block和油猴，应该都用不了，因为它窗口是拿canvas画出来的，不是一层套一层的html节点，这些插件都找不到页面上的元素。

所以最开始我才说前提是被官方收编
不过支持很困难吗。。。这个就没辙了。。。。感觉天使动漫至少在ui上得重新设计了，多少有点老了。。当初看到佬有整web就觉得可以转正，不过难搞+效果不好那就没辙了。。
