### ISSUE TITLE
关于发帖排行刷新的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#44]
https://github.com/user-attachments/assets/85d41e26-c205-460c-aebf-de93c2cba976

无意间发现的，没想到点了发帖排行的用户，在其个人主页刷新了一下就变成自己的个人主页了。。。操作流程见录屏

**Comment by Qing-Novel** [comment]
这块也有这个问题，感觉是看别人的个人主页，只要一刷新就变成自己的个人主页

https://github.com/user-attachments/assets/93948861-fbc4-456c-af7b-81885e023258

**Comment by realth000** [comment]
感谢，没这么操作过。

等我抽空修一下

**Comment by Qing-Novel** [comment]
> 感谢，没这么操作过。
> 
> 等我抽空修一下

好的，麻烦佬了

**Comment by realth000** [comment]
已修复 dd1eab1

**Comment by Qing-Novel** [comment]
> 已修复 [dd1eab1](https://github.com/realth000/tsdm_client/commit/dd1eab18f7238af430745a4be5e69e21e194cf18)

好的
