### ISSUE TITLE
关于个人主页退出动画的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#45]
应该不算bug，只是想问下佬，个人感觉这个退出动画有点奇怪，怎么会有两个头像。。。是佬这么设计的吗？
![2024_10_21_170402807](https://github.com/user-attachments/assets/e5cec09b-f9d2-4ce2-bec7-1011cc400063)

https://github.com/user-attachments/assets/c54691b1-d63e-4413-b3ce-b21198342321

**Comment by realth000** [comment]
是bug，在移动完全之前目标位置不应该有头像

**Comment by Qing-Novel** [comment]
> 是bug，在移动完全之前目标位置不应该有头像

好的

**Comment by realth000** [comment]
可以在帖子里点开楼层中其他用户的头像，那个动画是正确状态

**Comment by Qing-Novel** [comment]
> 可以在帖子里点开楼层中其他用户的头像，那个动画是正确状态

好的，坐等佬修复这个bug了

**Comment by realth000** [comment]
暂时不好修，先把这个动画去掉了

9a0416e

**Comment by Qing-Novel** [comment]
> 暂时不好修，先把这个动画去掉了
> 
> [9a0416e](https://github.com/realth000/tsdm_client/commit/9a0416ec1c9e4b9511f2acdd4eaf45519d037311)

好的
