### ISSUE TITLE
关于win版软件图标的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#46]
请问佬能增加win版软件图标的尺寸吗？目前的有点小，如果图标放的比较大就有框子
![QQ20241021-172306](https://github.com/user-attachments/assets/567a4a14-145b-46f4-9fbf-1a3c23e0e48c)
![4d6c7a8f-3f0d-458c-a999-6f7ed83dd0f4](https://github.com/user-attachments/assets/8a429f37-1574-46e8-a570-f629fc5fb2ed)

**Comment by Qing-Novel** [comment]
佬，是所有端的图标尺寸是一致的吗？

**Comment by Qing-Novel** [comment]
呃，是为了统一尺寸所以只能这样吗佬？

**Comment by realth000** [comment]
没有特意设置过，用工具生成的

**Comment by Qing-Novel** [comment]
> 没有特意设置过，用工具生成的

emmm那佬之后有计划调下尺寸吗？

**Comment by realth000** [comment]
windows上只生成有一个ico，暂时没计划调整。
之前做过一些分辨率大一些的图标，结果是小尺寸显示比较糊

**Comment by Qing-Novel** [comment]
> windows上只生成有一个ico，暂时没计划调整。 之前做过一些分辨率大一些的图标，结果是小尺寸显示比较糊

好吧。。。反正影响也不太影响。。。实在不行整快捷方式克服下

**Comment by realth000** [comment]
如果你有好的办法可以提，我这是直接用工具做，不一定最好，只是图省劲

**Comment by Qing-Novel** [comment]
我做了个图标，要不佬直接替换？
![1](https://github.com/user-attachments/assets/3eaa2e41-e269-4850-bb74-f8ae0128ebc5)

https://github.com/user-attachments/assets/ee324927-817b-4073-b707-62c31cf09d23

**Comment by realth000** [comment]
ico的吗？可以直接提pr，把windows/runner/resources里的ico换掉

**Comment by Qing-Novel** [comment]
> ico的吗？可以直接提pr，把windows/runner/resources里的ico换掉

是。行我试试，上次我不太会替换文件，我这次是电脑网页，我试试看

**Comment by Qing-Novel** [comment]
![image](https://github.com/user-attachments/assets/adf0a108-c65d-4385-9d6d-11a881c32b38)
我发您您替换下吧┗( ▔, ▔ )┛实在是不太会搞
[app_icon.zip](https://github.com/user-attachments/files/17477121/app_icon.zip)

**Comment by Qing-Novel** [comment]
> ico的吗？可以直接提pr，把windows/runner/resources里的ico换掉

折腾半天还是没替换成功😂我文件发这贴里了麻烦佬替换下吧

**Comment by Qing-Novel** [comment]
总算提交成功了。。。。佬待会儿看下吧

**Comment by Qing-Novel** [comment]
您再看下吧，是真的不会搞。。。

**Comment by Qing-Novel** [comment]
提pr了，.我先关了

**Comment by realth000** [comment]
合到这里了：  https://github.com/realth000/tsdm_client/actions/runs/11503715389

这个也带多用户登录

**Comment by Qing-Novel** [comment]
> 合到这里了： https://github.com/realth000/tsdm_client/actions/runs/11503715389
> 
> 这个也带多用户登录

OK

**Comment by realth000** [comment]
忘了开上传，用这个

https://github.com/realth000/tsdm_client/actions/runs/11510001567

**Comment by Qing-Novel** [comment]
> 忘了开上传，用这个
> 
> https://github.com/realth000/tsdm_client/actions/runs/11510001567

OK

**Comment by Qing-Novel** [comment]
> 忘了开上传，用这个
> 
> https://github.com/realth000/tsdm_client/actions/runs/11510001567

360脑子够有屎的，我就看个我之前答过题的活动贴，给我闪退报毒三次，我得把三个文件拉进白名单才看这个帖子不闪退，离了个大谱
![360截图20241025111108](https://github.com/user-attachments/assets/c0165898-1211-4c4b-8753-dd4fb9509caa)
![360截图20241025111057](https://github.com/user-attachments/assets/ff17199b-2213-438b-827e-db6fd75468a4)

**Comment by Qing-Novel** [comment]
> > 忘了开上传，用这个
> > https://github.com/realth000/tsdm_client/actions/runs/11510001567
> 
> 360脑子够有屎的，我就看个我之前答过题的活动贴，给我闪退报毒三次，我得把三个文件拉进白名单才看这个帖子不闪退，离了个大谱 ![360截图20241025111108](https://private-user-images.githubusercontent.com/136884931/379998928-c0165898-1211-4c4b-8753-dd4fb9509caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjMxNzMsIm5iZiI6MTcyOTg2Mjg3MywicGF0aCI6Ii8xMzY4ODQ5MzEvMzc5OTk4OTI4LWMwMTY1ODk4LTEyMTEtNGM0Yi04NzUzLWRkNGZiOTUwOWNhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMzI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2Y3NGViZjA0YjI0MWIwYTc5ZTk4YWVjYmFiNjIwMjI0ZGE3YWY2YjNmZjRiZDRjN2ZjMTE3NDdlNTFjMWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cE1qq_5NGffE_HdEhzDt74Q1aucCsGYrM3muwhjxhwM) ![360截图20241025111057](https://private-user-images.githubusercontent.com/136884931/379998934-ff17199b-2213-438b-827e-db6fd75468a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjMxNzMsIm5iZiI6MTcyOTg2Mjg3MywicGF0aCI6Ii8xMzY4ODQ5MzEvMzc5OTk4OTM0LWZmMTcxOTliLTIyMTMtNDM4Yi04MjdlLWRiNmZkNzU0NjhhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMzI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjg0YThhNjA1YzUxYzc4MmZlNTk1MDQ2MDRkZTI2M2YyY2UxYmE2MTY1YjAzNDc5OTc0YWI4NTJkNjI2NDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-SnN3Q_jyOhPdaWt0UUvdMDE0D0CT1Dl1bSWL1hm4XM)

虽然不搞这个貌似也可以，但是佬有没有计划搞下不让杀软报毒的优化吗？
