### ISSUE TITLE
关于搜索UI的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#48]
![IMG_20241021_194125](https://github.com/user-attachments/assets/91766c48-6c30-400e-b89e-cef533a7c3a3)
![2024_10_21_194024894](https://github.com/user-attachments/assets/cdc59de6-c1a3-4c8e-aaf6-e4b375add456)

https://github.com/user-attachments/assets/2daf14f6-be31-4662-856b-14055e8ada7c

好像搜索界面关键词这个内容被遮挡了

**Comment by Qing-Novel** [comment]
感觉这个就把元素往下移一点就可以解决了

**Comment by realth000** [comment]
应该是字体原因，这里的布局没有overflow，是正常的。

**Comment by Qing-Novel** [comment]
> 应该是字体原因，这里的布局没有overflow，是正常的。

好的

**Comment by Qing-Novel** [comment]
🤣像平板这种大点的屏幕的设备
![Screenshot_20241021_230859_kzs th000 tsdm_client](https://github.com/user-attachments/assets/583ebd3a-8f25-419c-94b1-441430bd4137)
就没这个问题
