### ISSUE TITLE
关于消息提醒疑似吞提醒的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#49]
我这几天发了20多个资源，刚才版主给我评分，我app里收到消息提醒后看到了对应个数的提醒条目，结果现在看就剩下一条了，是给折叠了吗？官方app是都在的

**Comment by Qing-Novel** [comment]
我仔细看了下，这20来条任务ID是一样的，是不是因为任务ID一样，app就算成是一条提醒了？
![Screenshot_20241021_200635_net tsdm tut](https://github.com/user-attachments/assets/8cff9179-2bff-4469-8fd3-d53ec52125f5)
![Screenshot_20241021_200809_kzs th000 tsdm_client](https://github.com/user-attachments/assets/c8b765cb-d754-40bf-bfd4-2c2c597eadac)

**Comment by realth000** [comment]
已经定位，不太好修，我看看怎么在保留数据的情况下修

**Comment by Qing-Novel** [comment]
> 已经定位，不太好修，我看看怎么在保留数据的情况下修

好的

**Comment by Qing-Novel** [comment]
感觉老可以先做数据备份功能再搞这个（.

**Comment by realth000** [comment]
应该是修好了，等后面遇到相同情况再验证吧

https://github.com/realth000/tsdm_client/actions/runs/11442739500

**Comment by Qing-Novel** [comment]
> 应该是修好了，等后面遇到相同情况再验证吧
> 
> https://github.com/realth000/tsdm_client/actions/runs/11442739500

好的，我最近会比较频繁的发资源，测是可以测的

**Comment by realth000** [comment]
不要用前面发的，用这个：

https://github.com/realth000/tsdm_client/actions/runs/11447773608

**Comment by Qing-Novel** [comment]
> 不要用前面发的，用这个：
> 
> https://github.com/realth000/tsdm_client/actions/runs/11447773608

好的

**Comment by Qing-Novel** [comment]
> 不要用前面发的，用这个：
> 
> https://github.com/realth000/tsdm_client/actions/runs/11447773608

这个版本我装到昨天晚上没打开app的设备上了，可以显示被吞了的提醒了
