### ISSUE TITLE
关于私人消息显示的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#50]
目前app私人消息的显示有一些混乱，就是如果别人给我发私人消息，我回复了，那别的设备上就看不到这个私人消息了（截图对比，两个是不同设备上的）
![Screenshot_20241021_205155_kzs th000 tsdm_client](https://github.com/user-attachments/assets/f4f08c1c-acfe-4a8c-b5bd-c29f6140497f)
![Screenshot_20241021_205224](https://github.com/user-attachments/assets/4d60580a-812d-4453-992b-99fcc73abbb3)
我觉得可以做成官方app这种跟一位用户交流的时候不管聊了多少条就显示一条卡片，卡片上显示最新地消息，同时体现是对方用户发的还是本人用户发的
![Screenshot_20241021_205148_net tsdm tut](https://github.com/user-attachments/assets/36045c00-821a-4453-adc2-f7766a990e2a)

**Comment by realth000** [comment]
已经发现了，会修

**Comment by Qing-Novel** [comment]
> 已经发现了，会修

好的好的，也麻烦佬看下另外一条消息提醒相关反馈的
