### ISSUE TITLE
关于个人主页图片加载的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#52]
感觉这个所有图片统一的一个一闪的加载有些奇怪，可以可以优化下看的比较自然些，记不太清楚之前是不是这样，就现在来看贼僵硬看着很别扭

https://github.com/user-attachments/assets/e2273d00-948e-4795-b3dd-64aef8aafd1c

**Comment by realth000** [comment]
因为会异步从缓存里加载，目前已经调整得比较好了，之前更烂（

后面会改，但不是短期内的。

**Comment by Qing-Novel** [comment]
> 因为会异步从缓存里加载，目前已经调整得比较好了，之前更烂（
> 
> 后面会改，但不是短期内的。

好的

**Comment by Qing-Novel** [comment]
> 因为会异步从缓存里加载，目前已经调整得比较好了，之前更烂（
> 
> 后面会改，但不是短期内的。

可以加个动画，就像官方app这样

https://github.com/user-attachments/assets/acc4eae9-c99d-45c6-a17c-046b239f4f7c
