### ISSUE TITLE
关于电脑版本的建议（手机端可以的话也能加上该功能，毕竟大的平板也会遇到该情况）

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#63]
请问佬未来可不可以加一个鼠标滚轮往上转的时候触发当前页面刷新 以及 帖子等界面有多页的时候当看到当前页面最底端时鼠标滚轮往下转触发下一页的内容 呢？有的软件就支持这两个功能，这样交互和使用起来会方便好多

**Comment by Qing-Novel** [comment]
像大一点的平板的话也会有使用鼠标使用软件的习惯（把平板作为轻办公机器使用）

**Comment by Qing-Novel** [comment]
ps：我看佬似乎也有在规划做webapp
![360截图20241025113545](https://github.com/user-attachments/assets/3502c672-754d-4fe2-9a5e-ade999ed9da1)
是打算功能做的差不多了再打包成webapp的版本吗（感觉可以找官方拉合作了233）

**Comment by realth000** [comment]
我个人太喜欢滚轮触发的方式，太容易误触。

针对宽屏后续会优化布局，比如加上web同款翻页，还有键盘快捷键，改布局这个事变动比较大，优先级很低，还是以移动端为主。

**Comment by Qing-Novel** [comment]
> 我个人太喜欢滚轮触发的方式，太容易误触。
> 
> 针对宽屏后续会优化布局，比如加上web同款翻页，还有键盘快捷键，改布局这个事变动比较大，优先级很低，还是以移动端为主。

好的
