### ISSUE TITLE
关于电脑端发帖时遇到的吞表情问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#65]
如录屏所示，文字打一半加一个表情再打就会吞表情，表情变成“￼”这个符号了，很奇怪，手机端从来没遇到过

https://github.com/user-attachments/assets/15d97e5d-ddd1-44e8-8be2-a531856c6293

**Comment by realth000** [comment]
嗯这是已知问题

**Comment by Qing-Novel** [comment]
> 嗯这是已知问题

好的

**Comment by realth000** [comment]
后面会集中修一波编辑器的问题

**Comment by Qing-Novel** [comment]
> 后面会集中修一波编辑器的问题

好的
佬，其他3个建议也麻烦看下吧
https://github.com/realth000/tsdm_client/issues/63
https://github.com/realth000/tsdm_client/issues/64
https://github.com/realth000/tsdm_client/issues/66
