### ISSUE TITLE
关于返回图片的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#66]
https://github.com/user-attachments/assets/85b399d4-8021-444e-a12c-c1eb740a9c78

这个返回图片佬要不改成点击后直接加载的形式吧，就别像带链接的图片这样的形式了吧

**Comment by realth000** [comment]
这样的话要固定识别这个跳转图片的url，不太想这样做。

其它例子包括本地已经自带表情了，浏览的帖子里的表情还是要下载一次，也是怕写死一些东西将来会导致问题。表情那个是体验实在太差才内置了，这个就不改了吧。

**Comment by Qing-Novel** [comment]
> 这样的话要固定识别这个跳转图片的url，不太想这样做。
> 
> 其它例子包括本地已经自带表情了，浏览的帖子里的表情还是要下载一次，也是怕写死一些东西将来会导致问题。表情那个是体验实在太差才内置了，这个就不改了吧。

好的

**Comment by Qing-Novel** [comment]
> 这样的话要固定识别这个跳转图片的url，不太想这样做。
> 
> 其它例子包括本地已经自带表情了，浏览的帖子里的表情还是要下载一次，也是怕写死一些东西将来会导致问题。表情那个是体验实在太差才内置了，这个就不改了吧。

佬，要不改下图片操作菜单的调出方式？之前都是单点就可以调出，要不改成单点是跳转到图片包含的链接，长按再弹出操作图片菜单？这样这问题就完美解决了

**Comment by realth000** [comment]
不能这样改，图片可能有链接，也可能没链接，还要能放大，一般来说长按操作越少越好。

**Comment by Qing-Novel** [comment]
> 不能这样改，图片可能有链接，也可能没链接，还要能放大，一般来说长按操作越少越好。

emmmm好吧
