### ISSUE TITLE
关于分区最新回复的时间问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#67]
![Screenshot_20241025_181754_kzs th000 tsdm_client](https://github.com/user-attachments/assets/9d7911a1-b8e8-47ec-8d4b-49313b17ef18)
多次看到这个最新回复时间是负数的情况了。。。

**Comment by Qing-Novel** [comment]
之前都下意识再刷新就没了，这次可我算是逮到录下来的机会了（

**Comment by Qing-Novel** [comment]
今天用app聊了一下午的天，这种情况看到好几次了
ps：用起来是真的爽，比官方app强太多了

**Comment by realth000** [comment]
这个是老问题，服务器那边时钟有误差，随着运行时间越长误差也会越大，去年年末服务器曾重启过一次，重启之前的误差是八分钟，现在也有一些误差了。

后面只能掩耳盗铃，把负数时间显示成0秒前，没办法彻底解决。

**Comment by Qing-Novel** [comment]
> 这个是老问题，服务器那边时钟有误差，随着运行时间越长误差也会越大，去年年末服务器曾重启过一次，重启之前的误差是八分钟，现在也有一些误差了。
> 
> 后面只能掩耳盗铃，把负数时间显示成0秒前，没办法彻底解决。

那只能掩耳盗铃了。。。。。确实这种问题app没法彻底修好。。
