### ISSUE TITLE
关于私信链接的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#69]
希望佬未来能支持私信链接点击后app内就可以私信而不是跳转到网页上

https://github.com/user-attachments/assets/494cd878-3e31-41d1-aca8-e7aabcf6691f

**Comment by realth000** [comment]
链接是什么格式的？我看看能不能支持

**Comment by Qing-Novel** [comment]
> 链接是什么格式的？我看看能不能支持

稍等下，我发您
https://www.tsdm39.com/home.php?mod=spacecp&ac=pm&op=showmsg&handlekey=showmsg_1889734&touid=1889734&pmid=0&daterange=2&pid=69981198&tid=1164497

**Comment by Qing-Novel** [comment]
> > 链接是什么格式的？我看看能不能支持
> 
> 稍等下，我发您 https://www.tsdm39.com/home.php?mod=spacecp&ac=pm&op=showmsg&handlekey=showmsg_1889734&touid=1889734&pmid=0&daterange=2&pid=69981198&tid=1164497

是这个链接佬，我是抄的某个好友个人签名里的链接（改下uid就是别人的私信链接了）

**Comment by realth000** [comment]
现在已经识别这种链接了，是个人签名里包含的这种链接会跳转到浏览器吗

**Comment by realth000** [comment]
检查链接的时候打错字了 - -

Fixed in 4a3e21f

**Comment by Qing-Novel** [comment]
好的
