### ISSUE TITLE
希望大佬可以加一个历史记录的功能

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#7]
有时候买资源的时候可能资源有问题，需要之后在买，或者看帖子之后还会看，有历史记录功能就方便找到需要看的帖子了，希望大佬可以做这个功能

**Comment by realth000** [comment]
可以做浏览历史记录。

1. 只能包含本机上浏览的帖子。
2. 多用户的情况下，可能要分用户，倾向于可以查看所有用户的历史记录。
3. 浏览的帖子多的话还是不好找，可以做个筛选。

**Comment by Qing-Novel** [comment]
> 可以做浏览历史记录。
> 
> 1. 只能包含本机上浏览的帖子。
> 2. 多用户的情况下，可能要分用户，倾向于可以查看所有用户的历史记录。
> 3. 浏览的帖子多的话还是不好找，可以做个筛选。

好的大佬，坐等更新

**Comment by realth000** [comment]
先关掉了，目前已经加上历史记录。

更多历史记录相关的功能例如筛选，删除，导入导出等，之后慢慢慢慢加吧。

**Comment by Qing-Novel** [comment]
> 先关掉了，目前已经加上历史记录。
> 
> 更多历史记录相关的功能例如筛选，删除，导入导出等，之后慢慢慢慢加吧。

好的
