### ISSUE TITLE
关于大屏幕（如电脑）下个人主页排版的建议

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#72]
如果屏幕过大（主要是长大于宽的比例下），个人主页的信息显示上就非常的有限，且感觉屏幕利用率过低
![个人主页0](https://github.com/user-attachments/assets/54346e4e-744b-4d17-9dc8-4ae7ebee4589)

感觉佬可以把个人主页底部的签到和统计信息模块拉上来，这样信息就比较集中看起来就方便多了（仿照佬在主页的处理做的示意图）
![个人主页1](https://github.com/user-attachments/assets/fb0f67ff-5aea-43e4-8edf-8fd3363ca267)

**Comment by Qing-Novel** [comment]
因为个人签名可能会放很多很大的图，而且相对来说不是那么重要，所以放底下且宽度跟屏幕几乎等宽就可以

**Comment by realth000** [comment]
目前没计划改这个布局，除非UI有bug或者改了以后好处很大不然不会大改。

桌面适配要等很靠后统一改吧。

**Comment by Qing-Novel** [comment]
> 目前没计划改这个布局，除非UI有bug或者改了以后好处很大不然不会大改。
> 
> 桌面适配要等很靠后统一改吧。

好的
