### ISSUE TITLE
关于私信不能连续发消息的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#73]
如录屏所示，基本上发完第一条后第二条就发不出去了（开了科学上网），只能退出当前聊天重进发送

https://github.com/user-attachments/assets/a95a6c0a-84c6-4727-bab7-9d7613549909

**Comment by realth000** [comment]
需要等等，服务器限制了大约10秒只能发送一次消息。

![image](https://github.com/user-attachments/assets/09dac884-c238-4fe8-9d68-d6c5aa70d112)

报错提示等下加上吧。

**Comment by Qing-Novel** [comment]
好的
