### ISSUE TITLE
关于自动签到的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#74]
可能开了后台运行的权限？今天无法自动签到

https://github.com/user-attachments/assets/3f66f797-7d36-4c8c-99a5-f8e8e6686a05

**Comment by Qing-Novel** [comment]
尝试强制关闭软件进程也无法自动签到

https://github.com/user-attachments/assets/ec7928e2-ee16-4a11-9e3d-eb53da446f93

**Comment by Qing-Novel** [comment]
是软件自行计时24小时候才触发自动签到吗（打开软件的时候）

**Comment by realth000** [comment]
Fixed in 6d06d2d

用这个：

https://github.com/realth000/tsdm_client/actions/runs/11542052955

**Comment by Qing-Novel** [comment]
> Fixed in [6d06d2d](https://github.com/realth000/tsdm_client/commit/6d06d2dfd495f70450b8e569f71943a429a01cba)
> 
> 用这个：
> 
> https://github.com/realth000/tsdm_client/actions/runs/11542052955

好的，我明天关注下佬这个有否完成自动签到（装完打开应该会强制自动签到一次

**Comment by realth000** [comment]
如果今天还没手动签到的话，装上以后，打开一次软件就签到了，会有提示

**Comment by Qing-Novel** [comment]
> 如果今天还没手动签到的话，装上以后，打开一次软件就签到了，会有提示

好的

**Comment by Qing-Novel** [comment]
报错了
![Screenshot_20241028_004101_kzs th000 tsdm_client](https://github.com/user-attachments/assets/6babf7ab-9613-4ac7-b264-8b8e75537a93)

**Comment by Qing-Novel** [comment]
重新打开软件后成功了（大号，小号是刚才签成功了）
![Screenshot_20241028_004252_kzs th000 tsdm_client](https://github.com/user-attachments/assets/bd16652a-ea82-4ec0-87f4-2904bcf5eb85)

**Comment by realth000** [comment]
我这里两个号可以一次签完。

再观察几天吧。

**Comment by Qing-Novel** [comment]
> 我这里两个号可以一次签完。
> 
> 再观察几天吧。

好的

**Comment by Qing-Novel** [comment]
今天软件打开内容不显示了
![Screenshot_20241028_075644_kzs th000 tsdm_client](https://github.com/user-attachments/assets/73c83de6-5c0d-4c51-8915-2ef6b0509927)
![Screenshot_20241028_075654_kzs th000 tsdm_client](https://github.com/user-attachments/assets/86cae7b4-d203-4fdf-ad13-b8723af2a55a)

**Comment by Qing-Novel** [comment]
> 我这里两个号可以一次签完。
> 
> 再观察几天吧。

今天还是报错
![Screenshot_20241029_000020_kzs th000 tsdm_client](https://github.com/user-attachments/assets/2e178fec-27d8-4b55-af6b-1a654f96fb02)

https://github.com/user-attachments/assets/fee48659-4b00-4069-91e9-31a9a355d27b

还是得开两次才可以签到完

**Comment by Qing-Novel** [comment]
签完到后切换账号：大号-小号-大号后报错
![Screenshot_20241029_000530_kzs th000 tsdm_client](https://github.com/user-attachments/assets/7b3714c8-1da1-4ddf-839a-847d0256233d)

**Comment by Qing-Novel** [comment]
> 明天把完整的签到报错贴出来吧

很长就是了。。根本没法截图发出来，我尝试录屏发或者图床发

**Comment by Qing-Novel** [comment]
。。。。。。居然没问题了

https://github.com/user-attachments/assets/1a928ad6-0309-4ead-b02d-3710ec8e18bc

我清了一次缓存。。。可能是因为这个

**Comment by realth000** [comment]
能用就行（）

**Comment by Qing-Novel** [comment]
> 能用就行（）

也是（.
