### ISSUE TITLE
关于消息提醒忽略的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#76]
我现在发现了这个
![Screenshot_20241029_093605](https://github.com/user-attachments/assets/2dead70e-dac9-4525-909a-ba71e88712d2)
不会评论被吞跟这个有关吧。。。不过我也不知道怎么关闭忽略

_Originally posted by @Qing-Novel in https://github.com/realth000/tsdm_client/issues/75#issuecomment-2442986947_

**Comment by realth000** [comment]
会覆盖的，重复的就不显示了。

至于这个重复怎么判定的，问过，不可知。

而且接口里拿不到这个重复通知的数量。

**Comment by Qing-Novel** [comment]
> 会覆盖的，重复的就不显示了。
> 
> 至于这个重复怎么判定的，问过，不可知。
> 
> 而且接口里拿不到这个重复通知的数量。

所以这个问题可以理解为无法修复吗。。。
然后可不可以被折叠时app的消息也不要同步，保留被折叠的消息？

**Comment by Qing-Novel** [comment]
现在是网页折叠app会同步折叠

**Comment by realth000** [comment]
对，服务器返回的消息一样的。
只是只有web能拿到重复的数量

**Comment by Qing-Novel** [comment]
> 对，服务器返回的消息一样的。 只是只有web能拿到重复的数量

所以这个问题就只能这样放着了还是佬后续会想办法？

**Comment by Qing-Novel** [comment]
只能说可惜了。。

**Comment by realth000** [comment]
除非说换回原来用网页拿信息的方式。
但是通知这部分是一定不会换回去的，这种方式效果太差了。

**Comment by Qing-Novel** [comment]
> 除非说换回原来用网页拿信息的方式。 但是通知这部分是一定不会换回去的，这种方式效果太差了。

就这样吧。。。再改回去，没必要。。。只能想办法克服了

**Comment by Qing-Novel** [comment]
等能系统推送消息就会好很多，现在没有只能打开app才知道，这个折叠就会漏消息，系统推送这个强提醒能减少漏看消息的几率，就坐等佬更新了
