### ISSUE TITLE
多账号切换的问题

### ISSUE THREAD

**Issue by aquausora** [realth000/tsdm_client#77]
今天使用中出现切换账号时，显示切换成功，但实际并没有成功切换的问题
转而使用网页版时，要求重新登录

客户端内重新登录一遍账户后，切换账户功能恢复正常
也许为cookie过期导致的？

**Comment by Qing-Novel** [comment]
> 今天使用中出现切换账号时，显示切换成功，但实际并没有成功切换的问题 转而使用网页版时，要求重新登录
> 
> 客户端内重新登录一遍账户后，切换账户功能恢复正常 也许为cookie过期导致的？

？就像我之前连续两天自动签到第一次失败一样，有些离谱的问题
不过我是没遇到过的，有弹出什么报错吗？

**Comment by aquausora** [comment]
> > 今天使用中出现切换账号时，显示切换成功，但实际并没有成功切换的问题 转而使用网页版时，要求重新登录
> > 客户端内重新登录一遍账户后，切换账户功能恢复正常 也许为cookie过期导致的？
> 
> ？就像我之前连续两天自动签到第一次失败一样，有些离谱的问题 不过我是没遇到过的，有弹出什么报错吗？

没有报错，只是提示了「切换成功」

**Comment by Qing-Novel** [comment]
> > > 今天使用中出现切换账号时，显示切换成功，但实际并没有成功切换的问题 转而使用网页版时，要求重新登录
> > > 客户端内重新登录一遍账户后，切换账户功能恢复正常 也许为cookie过期导致的？
> > 
> > 
> > ？就像我之前连续两天自动签到第一次失败一样，有些离谱的问题 不过我是没遇到过的，有弹出什么报错吗？
> 
> 没有报错，只是提示了「切换成功」

切换成功后返回首页了吗，如果首页刷新后还是没切换那才是出问题了

**Comment by aquausora** [comment]
> > > > 今天使用中出现切换账号时，显示切换成功，但实际并没有成功切换的问题 转而使用网页版时，要求重新登录
> > > > 客户端内重新登录一遍账户后，切换账户功能恢复正常 也许为cookie过期导致的？
> > > 
> > > 
> > > ？就像我之前连续两天自动签到第一次失败一样，有些离谱的问题 不过我是没遇到过的，有弹出什么报错吗？
> > 
> > 
> > 没有报错，只是提示了「切换成功」
> 
> 切换成功后返回首页了吗，如果首页刷新后还是没切换那才是出问题了

嗯，返回首页了，确实未切换成功
且重启app之后也是同样的情况
重新登录一遍目标账户后才成功完成切换

**Comment by Qing-Novel** [comment]
我有过类似的情况，只不过是app没登陆过某个账号结果APp里有，然后就跟你的情况一样。我这个原因就是分身应用的数据导致的

**Comment by aquausora** [comment]
> > > > > > 今天使用中出现切换账号时，显示切换成功，但实际并没有成功切换的问题 转而使用网页版时，要求重新登录
> > > > > > 客户端内重新登录一遍账户后，切换账户功能恢复正常 也许为cookie过期导致的？
> > > > > 
> > > > > 
> > > > > ？就像我之前连续两天自动签到第一次失败一样，有些离谱的问题 不过我是没遇到过的，有弹出什么报错吗？
> > > > 
> > > > 
> > > > 没有报错，只是提示了「切换成功」
> > > 
> > > 
> > > 切换成功后返回首页了吗，如果首页刷新后还是没切换那才是出问题了
> > 
> > 
> > 嗯，返回首页了，确实未切换成功 且重启app之后也是同样的情况 重新登录一遍目标账户后才成功完成切换
> 
> 你之前做过应用分身或者通过给软件改包名做分身软件吗？

没有，硬要说运行环境出了什么变动的话，昨晚我升级了Android 15
但是今早的切换也是正常的，到了中午才出现问题

**Comment by Qing-Novel** [comment]
> > > > > > > 今天使用中出现切换账号时，显示切换成功，但实际并没有成功切换的问题 转而使用网页版时，要求重新登录
> > > > > > > 客户端内重新登录一遍账户后，切换账户功能恢复正常 也许为cookie过期导致的？
> > > > > > 
> > > > > > 
> > > > > > ？就像我之前连续两天自动签到第一次失败一样，有些离谱的问题 不过我是没遇到过的，有弹出什么报错吗？
> > > > > 
> > > > > 
> > > > > 没有报错，只是提示了「切换成功」
> > > > 
> > > > 
> > > > 切换成功后返回首页了吗，如果首页刷新后还是没切换那才是出问题了
> > > 
> > > 
> > > 嗯，返回首页了，确实未切换成功 且重启app之后也是同样的情况 重新登录一遍目标账户后才成功完成切换
> > 
> > 
> > 你之前做过应用分身或者通过给软件改包名做分身软件吗？
> 
> 没有，硬要说运行环境出了什么变动的话，昨晚我升级了Android 15 但是今早的切换也是正常的，到了中午才出现问题

估计是偶发问题。。。

**Comment by aquausora** [comment]
> 我有过类似的情况，只不过是app没登陆过某个账号结果APp里有，然后就跟你的情况一样。我这个原因就是分身应用的数据导致的

是这样啊，我这边倒是可以再观察一段时间看看能否复现

**Comment by Qing-Novel** [comment]
> > 我有过类似的情况，只不过是app没登陆过某个账号结果APp里有，然后就跟你的情况一样。我这个原因就是分身应用的数据导致的
> 
> 是这样啊，我这边倒是可以再观察一段时间看看能否复现

毕竟有的偶发问题是真的难解决。。

**Comment by realth000** [comment]
切换到网页版要求重新登录是什么意思，修改过帐户密码么？

切换的时候做了容错，可能是误判成登录成功导致没生效。

**Comment by realth000** [comment]
可能是cookie过期，过去的版本cookie过期时间大约是一个月，不确定（

**Comment by aquausora** [comment]
> 切换到网页版要求重新登录是什么意思，修改过帐户密码么？
> 
> 切换的时候做了容错，可能是误判成登录成功导致没生效。

这个应该单纯就是浏览器存的cookie过期了

**Comment by realth000** [comment]
> > 可能是cookie过期，过去的版本cookie过期时间大约是一个月，不确定（
> 
> 那佬，现在是多长时间啊？

看了一眼，没看出来是多久（
