### ISSUE TITLE
关于消息功能

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#8]
请问大佬，关于消息有没有做想官方app那样有消息就会在系统的消息中心弹通知的功能呢？如果没有的话能否之后增加这一功能呢？

**Comment by realth000** [comment]
通知是什么时候触发的，打开app发现收到新消息么，是提醒还是私信啊？

我平时是关了通知用所以目前没想到做这个功能。
刚才开通知试了试，没有触发。

现在看通知必须要回到主界面并且主动刷新，并不方便。
未来计划会在大部分页面顶部右上角加一个消息按钮，进出一个页面的时候检测是否有新消息，有的话显示个小红点之类的（和现在主界面提示有通知的方式类似）。
当然这个功能并不和系统通知冲突，系统通知也可以做。

但是有个问题，由于软件并没有使用官方app的api（api没有公开），检查是否有消息的方式只能在**提醒/消息页面以外**检查，因为一但点进去（向服务器请求一次提醒/消息的页面），服务器那边会认为用户看过通知了，后续再请求任何页面都会显示没有未读通知。
所以，即使是做系统通知，也只能做到`有新提醒`和`收到x条短消息`这种程度，不能写出通知的具体内容。

要做的话，倾向于单独为安卓做一个系统通知，其他平台可能不会做（我没有苹果设备，桌面上这样用系统通知的软件很少）。

**Comment by Qing-Novel** [comment]
> 通知是什么时候触发的，打开app发现收到新消息么，是提醒还是私信啊？
> 
> 我平时是关了通知用所以目前没想到做这个功能。 刚才开通知试了试，没有触发。
> 
> 现在看通知必须要回到主界面并且主动刷新，并不方便。 未来计划会在大部分页面顶部右上角加一个消息按钮，进出一个页面的时候检测是否有新消息，有的话显示个小红点之类的（和现在主界面提示有通知的方式类似）。 当然这个功能并不和系统通知冲突，系统通知也可以做。
> 
> 但是有个问题，由于软件并没有使用官方app的api（api没有公开），检查是否有消息的方式只能在**提醒/消息页面以外**检查，因为一但点进去（向服务器请求一次提醒/消息的页面），服务器那边会认为用户看过通知了，后续再请求任何页面都会显示没有未读通知。 所以，即使是做系统通知，也只能做到`有新提醒`和`收到x条短消息`这种程度，不能写出通知的具体内容。
> 
> 要做的话，倾向于单独为安卓做一个系统通知，其他平台可能不会做（我没有苹果设备，桌面上这样用系统通知的软件很少）。
> 
> ~还有，别叫我大佬了~

没办法显示具体内容有点伤。。。。不过有提醒那也还可以。。
好的好的，之后不叫了XD

**Comment by Qing-Novel** [comment]
> 通知是什么时候触发的，打开app发现收到新消息么，是提醒还是私信啊？
> 
> 我平时是关了通知用所以目前没想到做这个功能。 刚才开通知试了试，没有触发。
> 
> 现在看通知必须要回到主界面并且主动刷新，并不方便。 未来计划会在大部分页面顶部右上角加一个消息按钮，进出一个页面的时候检测是否有新消息，有的话显示个小红点之类的（和现在主界面提示有通知的方式类似）。 当然这个功能并不和系统通知冲突，系统通知也可以做。
> 
> 但是有个问题，由于软件并没有使用官方app的api（api没有公开），检查是否有消息的方式只能在**提醒/消息页面以外**检查，因为一但点进去（向服务器请求一次提醒/消息的页面），服务器那边会认为用户看过通知了，后续再请求任何页面都会显示没有未读通知。 所以，即使是做系统通知，也只能做到`有新提醒`和`收到x条短消息`这种程度，不能写出通知的具体内容。
> 
> 要做的话，倾向于单独为安卓做一个系统通知，其他平台可能不会做（我没有苹果设备，桌面上这样用系统通知的软件很少）。
> 
> ~还有，别叫我大佬了~

要是作者后续做系统的消息推送，可以做到显示消息类型吗？比如 您收到了一条私信 或者 您收到了一条回复 之类的

**Comment by realth000** [comment]
> > 通知是什么时候触发的，打开app发现收到新消息么，是提醒还是私信啊？
> > 
> > 我平时是关了通知用所以目前没想到做这个功能。 刚才开通知试了试，没有触发。
> > 
> > 现在看通知必须要回到主界面并且主动刷新，并不方便。 未来计划会在大部分页面顶部右上角加一个消息按钮，进出一个页面的时候检测是否有新消息，有的话显示个小红点之类的（和现在主界面提示有通知的方式类似）。 当然这个功能并不和系统通知冲突，系统通知也可以做。
> > 
> > 但是有个问题，由于软件并没有使用官方app的api（api没有公开），检查是否有消息的方式只能在**提醒/消息页面以外**检查，因为一但点进去（向服务器请求一次提醒/消息的页面），服务器那边会认为用户看过通知了，后续再请求任何页面都会显示没有未读通知。 所以，即使是做系统通知，也只能做到`有新提醒`和`收到x条短消息`这种程度，不能写出通知的具体内容。
> > 
> > 要做的话，倾向于单独为安卓做一个系统通知，其他平台可能不会做（我没有苹果设备，桌面上这样用系统通知的软件很少）。
> > 
> > ~还有，别叫我大佬了~
> 
> 要是作者后续做系统的消息推送，可以做到显示消息类型吗？比如 您收到了一条私信 或者 您收到了一条回复 之类的

1. 收到新提醒
2. 收到x条私信
3. 收到新提醒和x条私信

大概是这个效果，和网页端提示的内容一样（提醒不知道条数）

想问问你想要什么时候触发通知呢？

采用进入新页面的时候探测一下是否有新消息这种方式的话，上面说的计划在右上角加的消息按钮能满足需求了，这种情况弹一个系统通知吗？

**Comment by Qing-Novel** [comment]
> > > 通知是什么时候触发的，打开app发现收到新消息么，是提醒还是私信啊？
> > > 我平时是关了通知用所以目前没想到做这个功能。 刚才开通知试了试，没有触发。
> > > 现在看通知必须要回到主界面并且主动刷新，并不方便。 未来计划会在大部分页面顶部右上角加一个消息按钮，进出一个页面的时候检测是否有新消息，有的话显示个小红点之类的（和现在主界面提示有通知的方式类似）。 当然这个功能并不和系统通知冲突，系统通知也可以做。
> > > 但是有个问题，由于软件并没有使用官方app的api（api没有公开），检查是否有消息的方式只能在**提醒/消息页面以外**检查，因为一但点进去（向服务器请求一次提醒/消息的页面），服务器那边会认为用户看过通知了，后续再请求任何页面都会显示没有未读通知。 所以，即使是做系统通知，也只能做到`有新提醒`和`收到x条短消息`这种程度，不能写出通知的具体内容。
> > > 要做的话，倾向于单独为安卓做一个系统通知，其他平台可能不会做（我没有苹果设备，桌面上这样用系统通知的软件很少）。
> > > ~还有，别叫我大佬了~
> > 
> > 
> > 要是作者后续做系统的消息推送，可以做到显示消息类型吗？比如 您收到了一条私信 或者 您收到了一条回复 之类的
> 
> 1. 收到新提醒
> 2. 收到x条私信
> 3. 收到新提醒和x条私信
> 
> 大概是这个效果，和网页端提示的内容一样（提醒不知道条数）
> 
> 想问问你想要什么时候触发通知呢？
> 
> 采用进入新页面的时候探测一下是否有新消息这种方式的话，上面说的计划在右上角加的消息按钮能满足需求了，这种情况弹一个系统通知吗？

主要是想像官方app那种就算没开软件，手机系统弹消息提示

**Comment by realth000** [comment]
官方有这个功能嘛？这种要服务端推送 + 有系统推送才行吧。

窝这没试出来有这种功能，至少要保持app打开。

**Comment by Qing-Novel** [comment]
> 官方有这个功能嘛？这种要服务端推送 + 有系统推送才行吧。
> 
> 窝这没试出来有这种功能，至少要保持app打开。

有，不过你得开一次app，之后软件就算关了也可以推送消息

**Comment by realth000** [comment]
> > 官方有这个功能嘛？这种要服务端推送 + 有系统推送才行吧。
> > 
> > 窝这没试出来有这种功能，至少要保持app打开。
> 
> 有，不过你得开一次app，之后软件就算关了也可以推送消息

emm没有发现有这个功能，触发不出来

可以做成一段时间内无切页面操作（也包括切到别的app）的时候定时刷一下是否有消息，有消息弹通知这种

**Comment by realth000** [comment]
我找个时间问一下吧，看能不能要一份接口。

要是能用接口的话很多棘手的事情（不光通知）都可以解决。
要来接口以后，用起来恐怕需要一段时间，用接口和现在的实现方式差别太大，把接口融进去需要时间，又要重构了。

**Comment by Qing-Novel** [comment]
> 我找个时间问一下吧，看能不能要一份接口。
> 
> 要是能用接口的话很多棘手的事情（不光通知）都可以解决。 要来接口以后，用起来恐怕需要一段时间，用接口和现在的实现方式差别太大，把接口融进去需要时间，又要重构了。

我录了一个录屏，给作者您看下（超10mb就传不上去是真恶心，录个屏还得剪辑无用片段和压缩帧率和分辨率）

https://github.com/user-attachments/assets/81d65c7a-18c7-4dbe-9457-b7697d3ce5a2

**Comment by realth000** [comment]
还是不行，复现不出来。平常那样用，通知都不是稳定出现。已经改成1分钟刷新频率 + 后台放行。

这个功能会尽量做，最后的效果目前看是之前说的，进出页面刷新 + 定时拉取通知，但关闭app以后应该就不会有效果了。
会在1.0之后实现。

**Comment by Qing-Novel** [comment]
> 还是不行，复现不出来。平常那样用，通知都不是稳定出现。已经改成1分钟刷新频率 + 后台放行。
> 
> 这个功能会尽量做，最后的效果目前看是之前说的，进出页面刷新 + 定时拉取通知，但关闭app以后应该就不会有效果了。 会在1.0之后实现。

我是手机管家开了后台启动，忽略电池优化的，可能是因为这个

**Comment by Qing-Novel** [comment]
> 还是不行，复现不出来。平常那样用，通知都不是稳定出现。已经改成1分钟刷新频率 + 后台放行。
> 
> 这个功能会尽量做，最后的效果目前看是之前说的，进出页面刷新 + 定时拉取通知，但关闭app以后应该就不会有效果了。 会在1.0之后实现。

辛苦作者了

**Comment by Qing-Novel** [comment]
![Screenshot_20241002_232714_net tsdm tut](https://github.com/user-attachments/assets/daee7c4d-4baf-44bf-bbfd-6b4757e128d2)
感觉作者大大可以参考下官方app关于消息提醒方面的功能

**Comment by realth000** [comment]
> ![Screenshot_20241002_232714_net tsdm tut](https://private-user-images.githubusercontent.com/136884931/372925524-daee7c4d-4baf-44bf-bbfd-6b4757e128d2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTkyOTQsIm5iZiI6MTcyNzk1ODk5NCwicGF0aCI6Ii8xMzY4ODQ5MzEvMzcyOTI1NTI0LWRhZWU3YzRkLTRiYWYtNDRiZi1iYmZkLTZiNDc1N2UxMjhkMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMjM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODcwY2QwNThmZmEyMjc1YjllYzY2NGM5NzcxMjNlY2VlMGVmNWI1MzY4NzQzMDJlZmVmMDI3ODEwNGUyMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M1cVV_KTHRCGe7WrwQTvnJ7GmZhMKW_sM5jPzqBFF7Q) 感觉作者大大可以参考下官方app关于消息提醒方面的功能

是的，之前测试的时候调整过这些开关。也差不多是之前提到的内容，后台定时拉取消息。

等拿到具体接口以后再整理一下吧，消息这部分应该会迁移成官方的api，把目前做的很粗糙的地方去掉。

后台通知的话，可能要看看安卓原生的东西，我目前不太了解，先一步步来吧。

~~应该是在1.0版本以后了咳咳~~

**Comment by Qing-Novel** [comment]
> > ![Screenshot_20241002_232714_net tsdm tut](https://private-user-images.githubusercontent.com/136884931/372925524-daee7c4d-4baf-44bf-bbfd-6b4757e128d2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTkyOTQsIm5iZiI6MTcyNzk1ODk5NCwicGF0aCI6Ii8xMzY4ODQ5MzEvMzcyOTI1NTI0LWRhZWU3YzRkLTRiYWYtNDRiZi1iYmZkLTZiNDc1N2UxMjhkMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMjM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODcwY2QwNThmZmEyMjc1YjllYzY2NGM5NzcxMjNlY2VlMGVmNWI1MzY4NzQzMDJlZmVmMDI3ODEwNGUyMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M1cVV_KTHRCGe7WrwQTvnJ7GmZhMKW_sM5jPzqBFF7Q) 感觉作者大大可以参考下官方app关于消息提醒方面的功能
> 
> 是的，之前测试的时候调整过这些开关。也差不多是之前提到的内容，后台定时拉取消息。
> 
> 等拿到具体接口以后再整理一下吧，消息这部分应该会迁移成官方的api，把目前做的很粗糙的地方去掉。
> 
> 后台通知的话，可能要看看安卓原生的东西，我目前不太了解，先一步步来吧。
> 
> ~应该是在1.0版本以后了咳咳~

好的好的，辛苦作者了

**Comment by Qing-Novel** [comment]
哈哈，自动签到佬也做了，就差这个功能了，这个功能也有了就可以彻底卸载官方版本了（私信折叠小问题至少有，等佬后续修复）

**Comment by Qing-Novel** [comment]
！这个佬给做了！太好了！
