### ISSUE TITLE
回帖补充内容显示异常

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#81]
偶尔会如图所示，单纯的发了一个回帖后新发了一个回复，有时候就会这样出现代码
![Screenshot_20241101_143124_kzs th000 tsdm_client](https://github.com/user-attachments/assets/cadf7484-820f-4684-bacf-04ce61ce61cb)

**Comment by realth000** [comment]
这是服务器的问题，客户端无法解决，你用网页一样可以触发。

**Comment by Qing-Novel** [comment]
> 这是服务器的问题，客户端无法解决，你用网页一样可以触发。

好的
