### ISSUE TITLE
发帖功能排版错位

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#82]
![Screenshot_20241101_144713](https://github.com/user-attachments/assets/76615116-5ae3-4d5b-947d-94b3b90a9709)
右侧有白边，这个设备是第一次用来发帖，所以不知道这问题之前有没有

**Comment by Qing-Novel** [comment]
Uploading SVID_20241101_144915_1.mp4…

**Comment by Qing-Novel** [comment]
https://github.com/user-attachments/assets/a326621f-435b-4f9f-86ad-07cef0f8654b

**Comment by Qing-Novel** [comment]
这个问题是不是根bbcode一起修？

**Comment by realth000** [comment]
等我回去确认一下原因。
只改布局的话周末就能修

**Comment by Qing-Novel** [comment]
> 等我回去确认一下原因。 只改布局的话周末就能修

好的
