### ISSUE TITLE
头像动画错误

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#83]
之前反馈过类似的问题，这次是楼主某个贴里放自己另外一个贴的链接，点开后返回到第一个打开的链接时触发的，跟之前反馈的一样会同时有两个头像（大致一个位置上），附录屏（写活动的时候无意间发现的😂）

https://github.com/user-attachments/assets/c7548893-b77e-432d-9cb4-1eb3d41667d6

**Comment by realth000** [comment]
这个就先不改了，这样改下去要把所有的头像动画都关掉，难免有误伤。

先放着吧，也不关，后面把头像重构以后看看效果

**Comment by Qing-Novel** [comment]
> 这个就先不改了，这样改下去要把所有的头像动画都关掉，难免有误伤。
> 
> 先放着吧，也不关，后面把头像重构以后看看效果

OK

**Comment by realth000** [comment]
这个修不了，只能先关掉了

**Comment by Qing-Novel** [comment]
这个问题还是有

**Comment by realth000** [comment]
这个问题没找到办法修复。

遇到的概率不算高，如果因此关掉hero动画的话得不偿失，就先不改了。

**Comment by Qing-Novel** [comment]
> 这个问题没找到办法修复。
> 
> 遇到的概率不算高，如果因此关掉hero动画的话得不偿失，就先不改了。

好的
