### ISSUE TITLE
首页ui错位

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#84]
![Screenshot_20241104_212653_tv danmaku bili_edit_47121572188641](https://github.com/user-attachments/assets/75337927-9d18-42a6-9eab-cbc36d5f786f)
电脑端没试，不过有可能也这样
手机端分屏可以调整软件显示宽度，如果app显示宽度过窄会出现ui错位

**Comment by realth000** [comment]
这是因为太窄了，难说是不是正常的宽度（

**Comment by Qing-Novel** [comment]
> 这是因为太窄了，难说是不是正常的宽度（

好吧，那佬有适配的打算不？
