### ISSUE TITLE
关于悬赏的疑问

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#87]
刚才水区打开了一个有悬赏的帖子，但是app里没显示内容，不知道是佬没做还是出问题了
![360截图20241109190658](https://github.com/user-attachments/assets/6ee139ae-2c73-4cf7-9f3c-39d160ad2e13)

**Comment by realth000** [comment]
和悬赏没关系，是一楼里有的html tag没有识别

**Comment by Qing-Novel** [comment]
> 和悬赏没关系，是一楼里有的html tag没有识别

原来如此
