### ISSUE TITLE
关于数字居中的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#9]
1.0.0 第8个测试版
![Screenshot_20241002_160322_kzs th000 tsdm_client](https://github.com/user-attachments/assets/b9f334d4-a3ec-4855-b14d-ca7563d739fd)
数字不居中，且数字越大越不居中

**Comment by realth000** [comment]
已修复

在下一版本发布前可以先用这里打的包：https://github.com/realth000/tsdm_client/actions/runs/11153125023

* fixed in 63f9cff

**Comment by Qing-Novel** [comment]
> 已修复
> 
> 在下一版本发布前可以先用这里打的包：https://github.com/realth000/tsdm_client/actions/runs/11153125023
> 
> * fixed in [63f9cff](https://github.com/realth000/tsdm_client/commit/63f9cffca01c92c1ed41a0f2d3d3b039d7d2c9c9)

好的，辛苦作者了

**Comment by realth000** [comment]
> > 已修复
> > 
> > 在下一版本发布前可以先用这里打的包：https://github.com/realth000/tsdm_client/actions/runs/11153125023
> > 
> > * fixed in [63f9cff](https://github.com/realth000/tsdm_client/commit/63f9cffca01c92c1ed41a0f2d3d3b039d7d2c9c9)
> 
> 好的，辛苦作者了

打包里面包含了浏览记录的功能，有bug或者建议可以提。

ui我是没辙了，想不到好布局。

**Comment by Qing-Novel** [comment]
> > > 已修复
> > > 在下一版本发布前可以先用这里打的包：https://github.com/realth000/tsdm_client/actions/runs/11153125023
> > > 
> > > * fixed in [63f9cff](https://github.com/realth000/tsdm_client/commit/63f9cffca01c92c1ed41a0f2d3d3b039d7d2c9c9)
> > 
> > 
> > 好的，辛苦作者了
> 
> 打包里面包含了浏览记录的功能，有bug或者建议可以提。
> 
> ui我是没辙了，想不到好布局。

好的好的。目前的ui挺不错的了
