### ISSUE TITLE
系统消息提醒不提醒的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#90]
没想到佬居然这么快就做了系统消息提醒，但是这个提醒貌似只在软件打开后才会跳，不像官方app软件在后台也能跳消息
已录屏，控制了变量（电池优化佬做的app和官方app都是不允许，启动都是手动管理且开机自启、后台启动和关联启动全开，多任务页面（显示开了多少个app，不是开发这个那个）都清掉）
不过貌似只是私人消息有这个问题（刚才在压缩录屏的时候给我推了一条帖子的回复（有开梯子，不知道是不是梯子的关系），多任务界面没软件挂着），活动这个因为目前没有所以也不知道效果如何
不管怎么压都超10mb。。。我发个网盘链接吧
https://www.123865.com/s/cHt4jv-BUjIA?
提取码：W1rA

**Comment by Qing-Novel** [comment]
> 没想到佬居然这么快就做了系统消息提醒，但是这个提醒貌似只在软件打开后才会跳，不像官方app软件在后台也能跳消息 已录屏，控制了变量（电池优化佬做的app和官方app都是不允许，启动都是手动管理且开机自启、后台启动和关联启动全开，多任务页面（显示开了多少个app，不是开发这个那个）都清掉） 不过貌似只是私人消息有这个问题（刚才在压缩录屏的时候给我推了一条帖子的回复（有开梯子，不知道是不是梯子的关系），多任务界面没软件挂着），活动这个因为目前没有所以也不知道效果如何 不管怎么压都超10mb。。。我发个网盘链接吧 https://www.123865.com/s/cHt4jv-BUjIA? 提取码：W1rA

刚才打开app发现有新帖子回复系统没提醒。。。貌似没官方app那样稳定推送

**Comment by Qing-Novel** [comment]
我是把时间间隔调到1分钟了，不知道跟这个有没有关系（虽然官方app我调的也是一分钟就是了）

**Comment by Qing-Novel** [comment]
有时候正常推送消息有时候不推送消息，跟梯子无关

**Comment by Qing-Novel** [comment]
佬是不是没做允许唤醒/后台留存？
![Screenshot_20241110_140633](https://github.com/user-attachments/assets/855ba0ac-e399-4f24-994a-4acfc7a88e90)

**Comment by Qing-Novel** [comment]
确认是佬没做后台了，我多任务保留软件任务就能正常接收消息了。希望佬能做下官方app的那种允许唤醒

**Comment by realth000** [comment]
不会做service，目标只是在软件运行的时候有弹窗，彻底关掉软件以后拉取推送这种功能就不做了，那种有些毒瘤。

**Comment by realth000** [comment]
要是有想法提PR的话是欢迎的，只是我自己不想做这种功能，软件既然关掉了老实停止运行就好（
