### ISSUE TITLE
消息提示去不掉的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#91]
https://github.com/user-attachments/assets/4e775dbf-aff1-45b4-b2b3-fae55dc06fc3

点进去看了，标为已读都不行，一刷新就又蹦数字了

**Comment by Qing-Novel** [comment]
貌似跟点查看还是点帖子链接有一点关系，如果先点的查看就没了，如果先点的帖子链接那之后再点查看还是有提示，得右上角一键清除才行

**Comment by Qing-Novel** [comment]
出现了不止一次未读消息读完后刷新，之前读过的消息还有未读提示（红点），同时列表里每条有未读提示的消息都复制了一遍，列表里看到未读消息每条都是2条，再次刷新多出来的未读消息才消失，此时未读提示还是没消失，只能右上角一键清掉

**Comment by Qing-Novel** [comment]
像这种
![Screenshot_20241110_143716](https://github.com/user-attachments/assets/4b06a581-6b4f-4aba-b32f-5aacc0470fc6)

**Comment by realth000** [comment]
首页下拉忘了更新时间戳，

**Comment by Qing-Novel** [comment]
> 首页下拉忘了更新时间戳，

感谢修复

**Comment by realth000** [comment]
https://github.com/realth000/tsdm_client/actions/runs/11765106455

试试这个吧，我也有点晕了，按说是修好了

**Comment by Qing-Novel** [comment]
> https://github.com/realth000/tsdm_client/actions/runs/11765106455
> 
> 试试这个吧，我也有点晕了，按说是修好了

行，我试试

**Comment by Qing-Novel** [comment]
貌似没事了。不过我发现我发的私信居然也提醒。。。是佬这么设计的吗？
