### ISSUE TITLE
软件语言的问题

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#92]
怎么有两个英文。。。
![Screenshot_20241110_154830_kzs th000 tsdm_client](https://github.com/user-attachments/assets/2ca38143-eec4-4cdf-81cb-2d178d12910c)

**Comment by Qing-Novel** [comment]
是繁体中文选项显示成英语了

https://github.com/user-attachments/assets/379a6e90-fadc-4d85-9347-c8a3e6b949cf

**Comment by realth000** [comment]
这个之前发现了，不是大问题

**Comment by Qing-Novel** [comment]
> 这个之前发现了，不是大问题

那会修吗？

**Comment by realth000** [comment]
不着急，先往后放吧，按说翻译的这部分内容没有改过，之前是没问题的，不知道从啥时候开始出错了。

**Comment by Qing-Novel** [comment]
> 不着急，先往后放吧，按说翻译的这部分内容没有改过，之前是没问题的，不知道从啥时候开始出错了。

行
