### ISSUE TITLE
没到签到时间

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#97]
刚签到的
![Screenshot_20241117_000306_kzs th000 tsdm_client](https://github.com/user-attachments/assets/98ca2ea1-3a6b-4045-aa8d-272fe590d3d1)
有点神奇。。。。

**Comment by Qing-Novel** [comment]
重新软件三次都这样。。。。我尝试下手动迁到哪

**Comment by Qing-Novel** [comment]
？手动怎么也这样
![Screenshot_20241117_000611_kzs th000 tsdm_client](https://github.com/user-attachments/assets/54739046-a765-4ba8-a77f-afd3316cf9ef)

**Comment by realth000** [comment]
![image](https://github.com/user-attachments/assets/70af3ae3-00fb-4d02-8982-1486b6a00b77)

服务器返回的就是这样，可能是服务器有bug了，也可能是调整了签到策略。

以前是00:00 ~ 01:00之间无法在网页签到，应该是改回去了。

> 本社区规定的签到时间是自1:00到23:59时止，请您自己把握好时间来签到，避免超过规定时间

**Comment by Qing-Novel** [comment]
好的
